	IFND CLASSACTIONCD_I
CLASSACTIONCD_I	SET	1


;-----------------------------------------------------------------------------


* This file was created automatically by CatComp.
* Do NOT edit by hand!
*


	IFND EXEC_TYPES_I
	INCLUDE 'exec/types.i'
	ENDC

	IFD CATCOMP_ARRAY
CATCOMP_NUMBERS SET 1
CATCOMP_STRINGS SET 1
	ENDC

	IFD CATCOMP_CODE
CATCOMP_BLOCK SET 1
	ENDC


;-----------------------------------------------------------------------------


	IFD CATCOMP_NUMBERS

	XDEF TXT_HELP
TXT_HELP EQU 272
	XDEF TXT_ICONIFY
TXT_ICONIFY EQU 273
	XDEF TXT_PROJECT
TXT_PROJECT EQU 274
	XDEF TXT_QUIT
TXT_QUIT EQU 275
	XDEF TXT_PREFERENCES
TXT_PREFERENCES EQU 276
	XDEF TXT_ABOUT
TXT_ABOUT EQU 277
	XDEF ERR_NOLIB
ERR_NOLIB EQU 279
	XDEF TXT_INFORMATION
TXT_INFORMATION EQU 280
	XDEF TXT_COPYRIGHT
TXT_COPYRIGHT EQU 281
	XDEF TXT_SURE
TXT_SURE EQU 282
	XDEF TXT_DIR
TXT_DIR EQU 283
	XDEF TXT_MEMORY
TXT_MEMORY EQU 286
	XDEF TXT_UNKNOWN
TXT_UNKNOWN EQU 287
	XDEF TXT_REQERROR
TXT_REQERROR EQU 288
	XDEF TXT_YESNO
TXT_YESNO EQU 289
	XDEF TXT_SUREERROR
TXT_SUREERROR EQU 290
	XDEF TXT_ASSIGN
TXT_ASSIGN EQU 291
	XDEF TXT_CLONE
TXT_CLONE EQU 292
	XDEF TXT_DRAWER
TXT_DRAWER EQU 293
	XDEF TXT_VOLUME
TXT_VOLUME EQU 294
	XDEF TXT_OK
TXT_OK EQU 295
	XDEF TXT_CANCEL
TXT_CANCEL EQU 296
	XDEF TXT_DELOK
TXT_DELOK EQU 297
	XDEF MSG_MKDIR
MSG_MKDIR EQU 298
	XDEF TXT_NOCONFIG
TXT_NOCONFIG EQU 299
	XDEF TXT_CONFIGCORRUPT
TXT_CONFIGCORRUPT EQU 300
	XDEF TXT_CONFIGNOTVALID
TXT_CONFIGNOTVALID EQU 301
	XDEF ERR_GENERAL
ERR_GENERAL EQU 303
	XDEF ERR_NOICON
ERR_NOICON EQU 304
	XDEF ERR_WRONGPATH
ERR_WRONGPATH EQU 305
	XDEF ERR_FILENOTFOUND
ERR_FILENOTFOUND EQU 306
	XDEF ERR_NOAREXX
ERR_NOAREXX EQU 307
	XDEF ERR_NOXFD
ERR_NOXFD EQU 308
	XDEF ERR_NOTCRUNCHED
ERR_NOTCRUNCHED EQU 309
	XDEF ERR_NOTDATA
ERR_NOTDATA EQU 310
	XDEF ERR_NOTDECR
ERR_NOTDECR EQU 311
	XDEF TXT_RENAME
TXT_RENAME EQU 313
	XDEF TXT_FILEEXISTS
TXT_FILEEXISTS EQU 315
	XDEF TXT_CONFIRMREPLACE
TXT_CONFIRMREPLACE EQU 317
	XDEF TXT_COPYICONS
TXT_COPYICONS EQU 318
	XDEF TXT_CREATEICONS
TXT_CREATEICONS EQU 319
	XDEF TXT_DISPLAYINFO
TXT_DISPLAYINFO EQU 320
	XDEF TXT_SETTINGS
TXT_SETTINGS EQU 321
	XDEF TXT_SHOWDRAWERSFIRST
TXT_SHOWDRAWERSFIRST EQU 322
	XDEF TXT_BUTTDEV
TXT_BUTTDEV EQU 335
	XDEF TXT_BUTTN
TXT_BUTTN EQU 336
	XDEF TXT_BUTTMKDIR
TXT_BUTTMKDIR EQU 337
	XDEF TXT_BUTTPATH
TXT_BUTTPATH EQU 339
	XDEF TXT_PROG
TXT_PROG EQU 345
	XDEF TXT_COPYING
TXT_COPYING EQU 346
	XDEF TXT_DELETING
TXT_DELETING EQU 347
	XDEF TXT_MOVING
TXT_MOVING EQU 348
	XDEF TXT_SNAPSHOTWINDOW
TXT_SNAPSHOTWINDOW EQU 350
	XDEF TXT_YESALLNONENO
TXT_YESALLNONENO EQU 351
	XDEF TXT_HASICON
TXT_HASICON EQU 353
	XDEF ERR_NOCOPY
ERR_NOCOPY EQU 356
	XDEF ERR_NODEL
ERR_NODEL EQU 357
	XDEF ERR_NOMOVE
ERR_NOMOVE EQU 358
	XDEF TXT_ENTPAT
TXT_ENTPAT EQU 359
	XDEF TXT_NEWFILE
TXT_NEWFILE EQU 361
	XDEF TXT_OLDFILE
TXT_OLDFILE EQU 362
	XDEF TXT_MOVEAS
TXT_MOVEAS EQU 363
	XDEF TXT_DATESTRING
TXT_DATESTRING EQU 364
	XDEF TXT_DISPLAYTIME
TXT_DISPLAYTIME EQU 365
	XDEF TXT_BUTTABORT
TXT_BUTTABORT EQU 368
	XDEF TXT_DRAGBAR
TXT_DRAGBAR EQU 369
	XDEF TXT_TOOLBAR
TXT_TOOLBAR EQU 370
	XDEF TXT_VISIBLE
TXT_VISIBLE EQU 371
	XDEF TXT_BYTESSEL
TXT_BYTESSEL EQU 373
	XDEF TXT_CHECKING
TXT_CHECKING EQU 374
	XDEF TXT_DDSELECTED
TXT_DDSELECTED EQU 375
	XDEF TXT_NOTENOUGHSPACE
TXT_NOTENOUGHSPACE EQU 376
	XDEF TXT_CHECKFIT
TXT_CHECKFIT EQU 385
	XDEF TXT_DELETEICONS
TXT_DELETEICONS EQU 386
	XDEF TXT_GENERAL
TXT_GENERAL EQU 387
	XDEF TXT_HIGHDIRS
TXT_HIGHDIRS EQU 388
	XDEF TXT_ICONS
TXT_ICONS EQU 389
	XDEF TXT_LISTERS
TXT_LISTERS EQU 390
	XDEF TXT_SHOWIMAGES
TXT_SHOWIMAGES EQU 391
	XDEF TXT_USED
TXT_USED EQU 392
	XDEF TXT_BUTTPARENT
TXT_BUTTPARENT EQU 393
	XDEF TXT_NAME
TXT_NAME EQU 396
	XDEF TXT_SIZE
TXT_SIZE EQU 397
	XDEF TXT_DATE
TXT_DATE EQU 398
	XDEF TXT_BITS
TXT_BITS EQU 399
	XDEF TXT_BUTTDIR
TXT_BUTTDIR EQU 400
	XDEF TXT_BUTTDIR2
TXT_BUTTDIR2 EQU 401
	XDEF TXT_COPY
TXT_COPY EQU 402
	XDEF TXT_CUT
TXT_CUT EQU 403
	XDEF TXT_EDIT
TXT_EDIT EQU 404
	XDEF TXT_PASTE
TXT_PASTE EQU 405
	XDEF TXT_PATHNOTIFY
TXT_PATHNOTIFY EQU 406
	XDEF TXT_SEARCH
TXT_SEARCH EQU 407
	XDEF TXT_SELALL
TXT_SELALL EQU 408
	XDEF TXT_SELNONE
TXT_SELNONE EQU 409
	XDEF TXT_SELTOGGLE
TXT_SELTOGGLE EQU 410
	XDEF TXT_SELTYPE
TXT_SELTYPE EQU 411
	XDEF TXT_SELPATTERN
TXT_SELPATTERN EQU 412
	XDEF TXT_DELETE
TXT_DELETE EQU 413
	XDEF TXT_COPYAS
TXT_COPYAS EQU 414
	XDEF TXT_FILE
TXT_FILE EQU 415
	XDEF TXT_MOVE
TXT_MOVE EQU 416
	XDEF TXT_PACK
TXT_PACK EQU 417
	XDEF TXT_BUTTREFRESH
TXT_BUTTREFRESH EQU 418
	XDEF TXT_CREATEARCHIVE
TXT_CREATEARCHIVE EQU 419
	XDEF TXT_CREATESUBDIR
TXT_CREATESUBDIR EQU 420
	XDEF TXT_DELOKSINGLE
TXT_DELOKSINGLE EQU 421
	XDEF TXT_GENERIC
TXT_GENERIC EQU 422
	XDEF TXT_BUTTACTIVATE
TXT_BUTTACTIVATE EQU 423
	XDEF TXT_BUTTDEACTIVATE
TXT_BUTTDEACTIVATE EQU 424
	XDEF MSG_COMMENT
MSG_COMMENT EQU 427
	XDEF MSG_ARCHIVE
MSG_ARCHIVE EQU 428
	XDEF MSG_EXECUTABLE
MSG_EXECUTABLE EQU 430
	XDEF MSG_OPENWINDOW
MSG_OPENWINDOW EQU 431
	XDEF MSG_READABLE
MSG_READABLE EQU 432
	XDEF MSG_ROOTDIR
MSG_ROOTDIR EQU 433
	XDEF MSG_SCRIPT
MSG_SCRIPT EQU 434
	XDEF MSG_VOLUMES
MSG_VOLUMES EQU 435
	XDEF MSG_WRITABLE
MSG_WRITABLE EQU 436
	XDEF MSG_DELETABLE
MSG_DELETABLE EQU 437
	XDEF MSG_COMMENT8
MSG_COMMENT8 EQU 438
	XDEF MSG_DATE8
MSG_DATE8 EQU 439
	XDEF MSG_DATENOTVALID
MSG_DATENOTVALID EQU 440
	XDEF MSG_FILEALREADYEXISTS
MSG_FILEALREADYEXISTS EQU 441
	XDEF MSG_NAME8
MSG_NAME8 EQU 442
	XDEF MSG_PROTECTION8
MSG_PROTECTION8 EQU 443
	XDEF MSG_CANCEL1
MSG_CANCEL1 EQU 444
	XDEF MSG_OK1
MSG_OK1 EQU 445
	XDEF MSG_NOTRASHCANAVAILABLE
MSG_NOTRASHCANAVAILABLE EQU 446
	XDEF MSG_BUTTFUELGAUGE
MSG_BUTTFUELGAUGE EQU 448
	XDEF MSG_COUNTINGFILES
MSG_COUNTINGFILES EQU 449
	XDEF TXT_DELOKTRASH
TXT_DELOKTRASH EQU 450
	XDEF TXT_DELOKSINGLETRASH
TXT_DELOKSINGLETRASH EQU 451
	XDEF MSG_DEPROTECTFILE
MSG_DEPROTECTFILE EQU 452
	XDEF ERR_NOMKDIR
ERR_NOMKDIR EQU 453
	XDEF MSG_VERSION
MSG_VERSION EQU 454
	XDEF MSG_NOTAVAILABLE
MSG_NOTAVAILABLE EQU 455
	XDEF MSG_VERSION8
MSG_VERSION8 EQU 456
	XDEF MSG_COPYANDDELETE
MSG_COPYANDDELETE EQU 457
	XDEF MSG_PULLDOWNMENU
MSG_PULLDOWNMENU EQU 458
	XDEF MSG_REPLACEVERSION
MSG_REPLACEVERSION EQU 459
	XDEF MSG_SAVE1
MSG_SAVE1 EQU 460
	XDEF MSG_SHOWVERSION
MSG_SHOWVERSION EQU 461
	XDEF MSG_COUNTFILES
MSG_COUNTFILES EQU 462
	XDEF MSG_CREATE1
MSG_CREATE1 EQU 464
	XDEF MSG_ICON
MSG_ICON EQU 465
	XDEF MSG_NAMEOFDIR8
MSG_NAMEOFDIR8 EQU 466
	XDEF MSG_PLEASEENTERDIRNAME
MSG_PLEASEENTERDIRNAME EQU 467
	XDEF MSG_ASSIGNTITLE
MSG_ASSIGNTITLE EQU 470
	XDEF MSG_COPYTO
MSG_COPYTO EQU 471
	XDEF MSG_ERR_ASSIGN
MSG_ERR_ASSIGN EQU 472
	XDEF MSG_OPENWITH
MSG_OPENWITH EQU 473
	XDEF MSG_PATHS
MSG_PATHS EQU 474
	XDEF MSG_VISITEDPATHS
MSG_VISITEDPATHS EQU 475
	XDEF MSG_ASSIGNEXISTS
MSG_ASSIGNEXISTS EQU 476
	XDEF MSG_ASSIGNMAKE
MSG_ASSIGNMAKE EQU 477
	XDEF MSG_ASSIGNREPLACEADD
MSG_ASSIGNREPLACEADD EQU 478
	XDEF MSG_ASSIGNREMOVE
MSG_ASSIGNREMOVE EQU 479
	XDEF MSG_ASSIGNWANTREMOVE
MSG_ASSIGNWANTREMOVE EQU 480
	XDEF MSG_CLOSEWINDOW
MSG_CLOSEWINDOW EQU 481
	XDEF MSG_CONFIRMCHECKSIZE
MSG_CONFIRMCHECKSIZE EQU 482
	XDEF MSG_DDIRSDFILES
MSG_DDIRSDFILES EQU 483
	XDEF MSG_NORENAME
MSG_NORENAME EQU 484
	XDEF ERR_WRONGPREFS
ERR_WRONGPREFS EQU 485
	XDEF MSG_CONFIRMDELETE
MSG_CONFIRMDELETE EQU 486
	XDEF MSG_TOOLS
MSG_TOOLS EQU 487
	XDEF MSG_NOCOPYTOSUBDIR
MSG_NOCOPYTOSUBDIR EQU 488

	ENDC ; CATCOMP_NUMBERS


;-----------------------------------------------------------------------------


	IFD CATCOMP_STRINGS

	XDEF TXT_HELP_STR
TXT_HELP_STR: DC.B 'Help',$00
	XDEF TXT_ICONIFY_STR
TXT_ICONIFY_STR: DC.B 'Iconify',$00
	XDEF TXT_PROJECT_STR
TXT_PROJECT_STR: DC.B 'Project',$00
	XDEF TXT_QUIT_STR
TXT_QUIT_STR: DC.B 'Quit',$00
	XDEF TXT_PREFERENCES_STR
TXT_PREFERENCES_STR: DC.B 'Preferences',$00
	XDEF TXT_ABOUT_STR
TXT_ABOUT_STR: DC.B 'About',$00
	XDEF ERR_NOLIB_STR
ERR_NOLIB_STR: DC.B 'Library not found.',10,'Check the requirements.',$00
	XDEF TXT_INFORMATION_STR
TXT_INFORMATION_STR: DC.B 'Information',$00
	XDEF TXT_COPYRIGHT_STR
TXT_COPYRIGHT_STR: DC.B '%s',10,10,'© 2003 by Martin R. Elsner & Salim Gasmi',10,10,'You can contact the auth'
	DC.B 'or at :',10,10,'Martin R. Elsner',10,'Muesener Strasse 46',10,'57223 Kreuztal',10,'Germany',10,10
	DC.B 'Email: classaction@martin-elsner.de ',10,'Web: http://www.martin-elsner.de',$00
	XDEF TXT_SURE_STR
TXT_SURE_STR: DC.B 'Are you sure ?',$00
	XDEF TXT_DIR_STR
TXT_DIR_STR: DC.B 'Directory',$00
	XDEF TXT_MEMORY_STR
TXT_MEMORY_STR: DC.B 'Not Enough Memory ',10,10,'to load the file',$00
	XDEF TXT_UNKNOWN_STR
TXT_UNKNOWN_STR: DC.B 'Unknown',$00
	XDEF TXT_REQERROR_STR
TXT_REQERROR_STR: DC.B 'Syntax Error in REQ command',$00
	XDEF TXT_YESNO_STR
TXT_YESNO_STR: DC.B 'Yes|No',$00
	XDEF TXT_SUREERROR_STR
TXT_SUREERROR_STR: DC.B 'Syntax error in SURE command',$00
	XDEF TXT_ASSIGN_STR
TXT_ASSIGN_STR: DC.B 'Assign',$00
	XDEF TXT_CLONE_STR
TXT_CLONE_STR: DC.B 'Copy As',$00
	XDEF TXT_DRAWER_STR
TXT_DRAWER_STR: DC.B 'Drawer',$00
	XDEF TXT_VOLUME_STR
TXT_VOLUME_STR: DC.B 'Volume',$00
	XDEF TXT_OK_STR
TXT_OK_STR: DC.B 'Okay',$00
	XDEF TXT_CANCEL_STR
TXT_CANCEL_STR: DC.B 'Cancel',$00
	XDEF TXT_DELOK_STR
TXT_DELOK_STR: DC.B 'Do you really want to delete the entries %s, ... ?',$00
	XDEF MSG_MKDIR_STR
MSG_MKDIR_STR: DC.B 'Create new directory',$00
	XDEF TXT_NOCONFIG_STR
TXT_NOCONFIG_STR: DC.B 'Config file not found.',$00
	XDEF TXT_CONFIGCORRUPT_STR
TXT_CONFIGCORRUPT_STR: DC.B 'Your config file is corrupted.',$00
	XDEF TXT_CONFIGNOTVALID_STR
TXT_CONFIGNOTVALID_STR: DC.B 'Your config file is not a valid',10,'ClassAction config file.',$00
	XDEF ERR_GENERAL_STR
ERR_GENERAL_STR: DC.B 'An unspecified error has occured.',$00
	XDEF ERR_NOICON_STR
ERR_NOICON_STR: DC.B 'There is no icon!',$00
	XDEF ERR_WRONGPATH_STR
ERR_WRONGPATH_STR: DC.B 'This path does not exist!',$00
	XDEF ERR_FILENOTFOUND_STR
ERR_FILENOTFOUND_STR: DC.B 'File not found.',$00
	XDEF ERR_NOAREXX_STR
ERR_NOAREXX_STR: DC.B 'The ARexx port could not be opened.',$00
	XDEF ERR_NOXFD_STR
ERR_NOXFD_STR: DC.B 'Xfdmaster.library not found !!',10,'The autodecrunching function',10,'will be de'
	DC.B 'activated.',$00
	XDEF ERR_NOTCRUNCHED_STR
ERR_NOTCRUNCHED_STR: DC.B 'Not crunched.',$00
	XDEF ERR_NOTDATA_STR
ERR_NOTDATA_STR: DC.B 'Not a data file.',$00
	XDEF ERR_NOTDECR_STR
ERR_NOTDECR_STR: DC.B 'Not decrunched.',$00
	XDEF TXT_RENAME_STR
TXT_RENAME_STR: DC.B 'Rename',$00
	XDEF TXT_FILEEXISTS_STR
TXT_FILEEXISTS_STR: DC.B 'Do you want to replace',$00
	XDEF TXT_CONFIRMREPLACE_STR
TXT_CONFIRMREPLACE_STR: DC.B 'Confirm replace',$00
	XDEF TXT_COPYICONS_STR
TXT_COPYICONS_STR: DC.B 'Copy Icons',$00
	XDEF TXT_CREATEICONS_STR
TXT_CREATEICONS_STR: DC.B 'Create Icons',$00
	XDEF TXT_DISPLAYINFO_STR
TXT_DISPLAYINFO_STR: DC.B 'Display .info',$00
	XDEF TXT_SETTINGS_STR
TXT_SETTINGS_STR: DC.B 'Settings',$00
	XDEF TXT_SHOWDRAWERSFIRST_STR
TXT_SHOWDRAWERSFIRST_STR: DC.B 'Show drawers first',$00
	XDEF TXT_BUTTDEV_STR
TXT_BUTTDEV_STR: DC.B 'Show all devices',$00
	XDEF TXT_BUTTN_STR
TXT_BUTTN_STR: DC.B 'Show the given path',$00
	XDEF TXT_BUTTMKDIR_STR
TXT_BUTTMKDIR_STR: DC.B 'Create a new directory',$00
	XDEF TXT_BUTTPATH_STR
TXT_BUTTPATH_STR: DC.B 'Enter a path to list it',$00
	XDEF TXT_PROG_STR
TXT_PROG_STR: DC.B 'ClassAction',$00
	XDEF TXT_COPYING_STR
TXT_COPYING_STR: DC.B 'Copying',$00
	XDEF TXT_DELETING_STR
TXT_DELETING_STR: DC.B 'Deleting',$00
	XDEF TXT_MOVING_STR
TXT_MOVING_STR: DC.B 'Moving',$00
	XDEF TXT_SNAPSHOTWINDOW_STR
TXT_SNAPSHOTWINDOW_STR: DC.B 'Snapshot Window',$00
	XDEF TXT_YESALLNONENO_STR
TXT_YESALLNONENO_STR: DC.B 'Yes|All|None|No',$00
	XDEF TXT_HASICON_STR
TXT_HASICON_STR: DC.B 'has already an icon!',$00
	XDEF ERR_NOCOPY_STR
ERR_NOCOPY_STR: DC.B 'Could not copy %s !',$00
	XDEF ERR_NODEL_STR
ERR_NODEL_STR: DC.B 'Could not delete %s !',$00
	XDEF ERR_NOMOVE_STR
ERR_NOMOVE_STR: DC.B 'Could not move %s !',$00
	XDEF TXT_ENTPAT_STR
TXT_ENTPAT_STR: DC.B 'Enter Pattern',$00
	XDEF TXT_NEWFILE_STR
TXT_NEWFILE_STR: DC.B 'New file:',$00
	XDEF TXT_OLDFILE_STR
TXT_OLDFILE_STR: DC.B 'Old file:',$00
	XDEF TXT_MOVEAS_STR
TXT_MOVEAS_STR: DC.B 'Move As',$00
	XDEF TXT_DATESTRING_STR
TXT_DATESTRING_STR: DC.B 'Date as text',$00
	XDEF TXT_DISPLAYTIME_STR
TXT_DISPLAYTIME_STR: DC.B 'Display time',$00
	XDEF TXT_BUTTABORT_STR
TXT_BUTTABORT_STR: DC.B 'Abort the current process',$00
	XDEF TXT_DRAGBAR_STR
TXT_DRAGBAR_STR: DC.B 'Dragbar',$00
	XDEF TXT_TOOLBAR_STR
TXT_TOOLBAR_STR: DC.B 'Toolbar',$00
	XDEF TXT_VISIBLE_STR
TXT_VISIBLE_STR: DC.B 'Visible',$00
	XDEF TXT_BYTESSEL_STR
TXT_BYTESSEL_STR: DC.B '%s bytes selected',$00
	XDEF TXT_CHECKING_STR
TXT_CHECKING_STR: DC.B 'Checking',$00
	XDEF TXT_DDSELECTED_STR
TXT_DDSELECTED_STR: DC.B '%d selected / %d available',$00
	XDEF TXT_NOTENOUGHSPACE_STR
TXT_NOTENOUGHSPACE_STR: DC.B 'Not enough space!',$00
	XDEF TXT_CHECKFIT_STR
TXT_CHECKFIT_STR: DC.B 'Check space',$00
	XDEF TXT_DELETEICONS_STR
TXT_DELETEICONS_STR: DC.B 'Delete icons',$00
	XDEF TXT_GENERAL_STR
TXT_GENERAL_STR: DC.B 'General',$00
	XDEF TXT_HIGHDIRS_STR
TXT_HIGHDIRS_STR: DC.B 'Highlight dirs',$00
	XDEF TXT_ICONS_STR
TXT_ICONS_STR: DC.B 'Icons',$00
	XDEF TXT_LISTERS_STR
TXT_LISTERS_STR: DC.B 'Listers',$00
	XDEF TXT_SHOWIMAGES_STR
TXT_SHOWIMAGES_STR: DC.B 'Show images',$00
	XDEF TXT_USED_STR
TXT_USED_STR: DC.B 'used',$00
	XDEF TXT_BUTTPARENT_STR
TXT_BUTTPARENT_STR: DC.B 'Go to the parent directory',$00
	XDEF TXT_NAME_STR
TXT_NAME_STR: DC.B 'Name',$00
	XDEF TXT_SIZE_STR
TXT_SIZE_STR: DC.B 'Size',$00
	XDEF TXT_DATE_STR
TXT_DATE_STR: DC.B 'Date',$00
	XDEF TXT_BITS_STR
TXT_BITS_STR: DC.B 'Bits',$00
	XDEF TXT_BUTTDIR_STR
TXT_BUTTDIR_STR: DC.B 'Source',$00
	XDEF TXT_BUTTDIR2_STR
TXT_BUTTDIR2_STR: DC.B 'Destination',$00
	XDEF TXT_COPY_STR
TXT_COPY_STR: DC.B 'Copy',$00
	XDEF TXT_CUT_STR
TXT_CUT_STR: DC.B 'Cut',$00
	XDEF TXT_EDIT_STR
TXT_EDIT_STR: DC.B 'Edit',$00
	XDEF TXT_PASTE_STR
TXT_PASTE_STR: DC.B 'Paste',$00
	XDEF TXT_PATHNOTIFY_STR
TXT_PATHNOTIFY_STR: DC.B 'Update on changes',$00
	XDEF TXT_SEARCH_STR
TXT_SEARCH_STR: DC.B 'Search',$00
	XDEF TXT_SELALL_STR
TXT_SELALL_STR: DC.B 'Select all',$00
	XDEF TXT_SELNONE_STR
TXT_SELNONE_STR: DC.B 'Select nothing',$00
	XDEF TXT_SELTOGGLE_STR
TXT_SELTOGGLE_STR: DC.B 'Toggle selection',$00
	XDEF TXT_SELTYPE_STR
TXT_SELTYPE_STR: DC.B 'Select same type',$00
	XDEF TXT_SELPATTERN_STR
TXT_SELPATTERN_STR: DC.B 'Select pattern',$00
	XDEF TXT_DELETE_STR
TXT_DELETE_STR: DC.B 'Delete',$00
	XDEF TXT_COPYAS_STR
TXT_COPYAS_STR: DC.B 'Copy as',$00
	XDEF TXT_FILE_STR
TXT_FILE_STR: DC.B 'File',$00
	XDEF TXT_MOVE_STR
TXT_MOVE_STR: DC.B 'Move',$00
	XDEF TXT_PACK_STR
TXT_PACK_STR: DC.B 'Pack',$00
	XDEF TXT_BUTTREFRESH_STR
TXT_BUTTREFRESH_STR: DC.B 'Refresh this lister',$00
	XDEF TXT_CREATEARCHIVE_STR
TXT_CREATEARCHIVE_STR: DC.B 'Create archive',$00
	XDEF TXT_CREATESUBDIR_STR
TXT_CREATESUBDIR_STR: DC.B 'Create subdirectory',$00
	XDEF TXT_DELOKSINGLE_STR
TXT_DELOKSINGLE_STR: DC.B 'Do you really want to delete the entry %s ?',$00
	XDEF TXT_GENERIC_STR
TXT_GENERIC_STR: DC.B 'Generic',$00
	XDEF TXT_BUTTACTIVATE_STR
TXT_BUTTACTIVATE_STR: DC.B 'Activate lister',$00
	XDEF TXT_BUTTDEACTIVATE_STR
TXT_BUTTDEACTIVATE_STR: DC.B 'Deactivate lister',$00
	XDEF MSG_COMMENT_STR
MSG_COMMENT_STR: DC.B 'Comment',$00
	XDEF MSG_ARCHIVE_STR
MSG_ARCHIVE_STR: DC.B 'Archive',$00
	XDEF MSG_EXECUTABLE_STR
MSG_EXECUTABLE_STR: DC.B 'Executable',$00
	XDEF MSG_OPENWINDOW_STR
MSG_OPENWINDOW_STR: DC.B 'Open window',$00
	XDEF MSG_READABLE_STR
MSG_READABLE_STR: DC.B 'Readable',$00
	XDEF MSG_ROOTDIR_STR
MSG_ROOTDIR_STR: DC.B 'Root directory',$00
	XDEF MSG_SCRIPT_STR
MSG_SCRIPT_STR: DC.B 'Script',$00
	XDEF MSG_VOLUMES_STR
MSG_VOLUMES_STR: DC.B 'Volumes',$00
	XDEF MSG_WRITABLE_STR
MSG_WRITABLE_STR: DC.B 'Writable',$00
	XDEF MSG_DELETABLE_STR
MSG_DELETABLE_STR: DC.B 'Deletable',$00
	XDEF MSG_COMMENT8_STR
MSG_COMMENT8_STR: DC.B 'Comment:',$00
	XDEF MSG_DATE8_STR
MSG_DATE8_STR: DC.B 'Date:',$00
	XDEF MSG_DATENOTVALID_STR
MSG_DATENOTVALID_STR: DC.B 'The date is not valid !',$00
	XDEF MSG_FILEALREADYEXISTS_STR
MSG_FILEALREADYEXISTS_STR: DC.B 'This file already exists !',$00
	XDEF MSG_NAME8_STR
MSG_NAME8_STR: DC.B 'Name:',$00
	XDEF MSG_PROTECTION8_STR
MSG_PROTECTION8_STR: DC.B 'Protection:',$00
	XDEF MSG_CANCEL1_STR
MSG_CANCEL1_STR: DC.B '_Cancel',$00
	XDEF MSG_OK1_STR
MSG_OK1_STR: DC.B '_Ok',$00
	XDEF MSG_NOTRASHCANAVAILABLE_STR
MSG_NOTRASHCANAVAILABLE_STR: DC.B 'No trashcan available !',$00
	XDEF MSG_BUTTFUELGAUGE_STR
MSG_BUTTFUELGAUGE_STR: DC.B 'Click here to adjust the browser size',$00
	XDEF MSG_COUNTINGFILES_STR
MSG_COUNTINGFILES_STR: DC.B 'Counting Files ...',$00
	XDEF TXT_DELOKTRASH_STR
TXT_DELOKTRASH_STR: DC.B 'Do you really want to move the entries %s, ... into the trashcan ?',$00
	XDEF TXT_DELOKSINGLETRASH_STR
TXT_DELOKSINGLETRASH_STR: DC.B 'Do you really want to move the entry %s into the trashcan ?',$00
	XDEF MSG_DEPROTECTFILE_STR
MSG_DEPROTECTFILE_STR: DC.B 'The file %s is write protected.',10,' Shall I remove the protection for thi'
	DC.B 's file?',$00
	XDEF ERR_NOMKDIR_STR
ERR_NOMKDIR_STR: DC.B 'Could not create directory %s !',$00
	XDEF MSG_VERSION_STR
MSG_VERSION_STR: DC.B 'Version',$00
	XDEF MSG_NOTAVAILABLE_STR
MSG_NOTAVAILABLE_STR: DC.B 'not available',$00
	XDEF MSG_VERSION8_STR
MSG_VERSION8_STR: DC.B 'Version:',$00
	XDEF MSG_COPYANDDELETE_STR
MSG_COPYANDDELETE_STR: DC.B 'Copy and delete',$00
	XDEF MSG_PULLDOWNMENU_STR
MSG_PULLDOWNMENU_STR: DC.B 'Pulldown menu',$00
	XDEF MSG_REPLACEVERSION_STR
MSG_REPLACEVERSION_STR: DC.B 'Replace older versions',$00
	XDEF MSG_SAVE1_STR
MSG_SAVE1_STR: DC.B '_Save',$00
	XDEF MSG_SHOWVERSION_STR
MSG_SHOWVERSION_STR: DC.B 'Show version',$00
	XDEF MSG_COUNTFILES_STR
MSG_COUNTFILES_STR: DC.B 'Count Files',$00
	XDEF MSG_CREATE1_STR
MSG_CREATE1_STR: DC.B '_Create',$00
	XDEF MSG_ICON_STR
MSG_ICON_STR: DC.B 'Icon',$00
	XDEF MSG_NAMEOFDIR8_STR
MSG_NAMEOFDIR8_STR: DC.B 'Name of the directory:',$00
	XDEF MSG_PLEASEENTERDIRNAME_STR
MSG_PLEASEENTERDIRNAME_STR: DC.B 'Please enter the name of the new directory.',$00
	XDEF MSG_ASSIGNTITLE_STR
MSG_ASSIGNTITLE_STR: DC.B 'Please enter assign title:',$00
	XDEF MSG_COPYTO_STR
MSG_COPYTO_STR: DC.B 'Copy to',$00
	XDEF MSG_ERR_ASSIGN_STR
MSG_ERR_ASSIGN_STR: DC.B 'Assign could not be created. Please check if this assign already exist'
	DC.B 's.',$00
	XDEF MSG_OPENWITH_STR
MSG_OPENWITH_STR: DC.B 'Open with',$00
	XDEF MSG_PATHS_STR
MSG_PATHS_STR: DC.B 'Paths',$00
	XDEF MSG_VISITEDPATHS_STR
MSG_VISITEDPATHS_STR: DC.B 'Visited paths',$00
	XDEF MSG_ASSIGNEXISTS_STR
MSG_ASSIGNEXISTS_STR: DC.B 'This assign already exists.',$00
	XDEF MSG_ASSIGNMAKE_STR
MSG_ASSIGNMAKE_STR: DC.B 'Make assign',$00
	XDEF MSG_ASSIGNREPLACEADD_STR
MSG_ASSIGNREPLACEADD_STR: DC.B 'Replace|Add|Cancel',$00
	XDEF MSG_ASSIGNREMOVE_STR
MSG_ASSIGNREMOVE_STR: DC.B 'Remove assign',$00
	XDEF MSG_ASSIGNWANTREMOVE_STR
MSG_ASSIGNWANTREMOVE_STR: DC.B 'Do you really want to remove this assign?',$00
	XDEF MSG_CLOSEWINDOW_STR
MSG_CLOSEWINDOW_STR: DC.B 'Please close all windows on this screen.',$00
	XDEF MSG_CONFIRMCHECKSIZE_STR
MSG_CONFIRMCHECKSIZE_STR: DC.B 'The volume reports 0 bytes of free space. Do you want to continue?',$00
	XDEF MSG_DDIRSDFILES_STR
MSG_DDIRSDFILES_STR: DC.B '%d/%d directories, %d/%d files',$00
	XDEF MSG_NORENAME_STR
MSG_NORENAME_STR: DC.B 'Could not rename %s !',$00
	XDEF ERR_WRONGPREFS_STR
ERR_WRONGPREFS_STR: DC.B 'This is an old preference file.',10,'Please start ClassActionPrefs and save'
	DC.B ' your preferences.',10,'Check if you are using the correct version of Class'
	DC.B 'Action and ClassActionPrefs.',$00
	XDEF MSG_CONFIRMDELETE_STR
MSG_CONFIRMDELETE_STR: DC.B 'Confirm delete',$00
	XDEF MSG_TOOLS_STR
MSG_TOOLS_STR: DC.B 'Tools',$00
	XDEF MSG_NOCOPYTOSUBDIR_STR
MSG_NOCOPYTOSUBDIR_STR: DC.B 'It',39,'s not allowed to copy directories into any subdir!',$00

	ENDC ; CATCOMP_STRINGS


;-----------------------------------------------------------------------------


	IFD CATCOMP_ARRAY

   STRUCTURE CatCompArrayType,0
	LONG cca_ID
	APTR cca_Str
   LABEL CatCompArrayType_SIZEOF

	CNOP 0,4

	XDEF CatCompArray
CatCompArray:
	XDEF _CatCompArray
_CatCompArray:
AS0:	DC.L TXT_HELP,TXT_HELP_STR
AS1:	DC.L TXT_ICONIFY,TXT_ICONIFY_STR
AS2:	DC.L TXT_PROJECT,TXT_PROJECT_STR
AS3:	DC.L TXT_QUIT,TXT_QUIT_STR
AS4:	DC.L TXT_PREFERENCES,TXT_PREFERENCES_STR
AS5:	DC.L TXT_ABOUT,TXT_ABOUT_STR
AS6:	DC.L ERR_NOLIB,ERR_NOLIB_STR
AS7:	DC.L TXT_INFORMATION,TXT_INFORMATION_STR
AS8:	DC.L TXT_COPYRIGHT,TXT_COPYRIGHT_STR
AS9:	DC.L TXT_SURE,TXT_SURE_STR
AS10:	DC.L TXT_DIR,TXT_DIR_STR
AS11:	DC.L TXT_MEMORY,TXT_MEMORY_STR
AS12:	DC.L TXT_UNKNOWN,TXT_UNKNOWN_STR
AS13:	DC.L TXT_REQERROR,TXT_REQERROR_STR
AS14:	DC.L TXT_YESNO,TXT_YESNO_STR
AS15:	DC.L TXT_SUREERROR,TXT_SUREERROR_STR
AS16:	DC.L TXT_ASSIGN,TXT_ASSIGN_STR
AS17:	DC.L TXT_CLONE,TXT_CLONE_STR
AS18:	DC.L TXT_DRAWER,TXT_DRAWER_STR
AS19:	DC.L TXT_VOLUME,TXT_VOLUME_STR
AS20:	DC.L TXT_OK,TXT_OK_STR
AS21:	DC.L TXT_CANCEL,TXT_CANCEL_STR
AS22:	DC.L TXT_DELOK,TXT_DELOK_STR
AS23:	DC.L MSG_MKDIR,MSG_MKDIR_STR
AS24:	DC.L TXT_NOCONFIG,TXT_NOCONFIG_STR
AS25:	DC.L TXT_CONFIGCORRUPT,TXT_CONFIGCORRUPT_STR
AS26:	DC.L TXT_CONFIGNOTVALID,TXT_CONFIGNOTVALID_STR
AS27:	DC.L ERR_GENERAL,ERR_GENERAL_STR
AS28:	DC.L ERR_NOICON,ERR_NOICON_STR
AS29:	DC.L ERR_WRONGPATH,ERR_WRONGPATH_STR
AS30:	DC.L ERR_FILENOTFOUND,ERR_FILENOTFOUND_STR
AS31:	DC.L ERR_NOAREXX,ERR_NOAREXX_STR
AS32:	DC.L ERR_NOXFD,ERR_NOXFD_STR
AS33:	DC.L ERR_NOTCRUNCHED,ERR_NOTCRUNCHED_STR
AS34:	DC.L ERR_NOTDATA,ERR_NOTDATA_STR
AS35:	DC.L ERR_NOTDECR,ERR_NOTDECR_STR
AS36:	DC.L TXT_RENAME,TXT_RENAME_STR
AS37:	DC.L TXT_FILEEXISTS,TXT_FILEEXISTS_STR
AS38:	DC.L TXT_CONFIRMREPLACE,TXT_CONFIRMREPLACE_STR
AS39:	DC.L TXT_COPYICONS,TXT_COPYICONS_STR
AS40:	DC.L TXT_CREATEICONS,TXT_CREATEICONS_STR
AS41:	DC.L TXT_DISPLAYINFO,TXT_DISPLAYINFO_STR
AS42:	DC.L TXT_SETTINGS,TXT_SETTINGS_STR
AS43:	DC.L TXT_SHOWDRAWERSFIRST,TXT_SHOWDRAWERSFIRST_STR
AS44:	DC.L TXT_BUTTDEV,TXT_BUTTDEV_STR
AS45:	DC.L TXT_BUTTN,TXT_BUTTN_STR
AS46:	DC.L TXT_BUTTMKDIR,TXT_BUTTMKDIR_STR
AS47:	DC.L TXT_BUTTPATH,TXT_BUTTPATH_STR
AS48:	DC.L TXT_PROG,TXT_PROG_STR
AS49:	DC.L TXT_COPYING,TXT_COPYING_STR
AS50:	DC.L TXT_DELETING,TXT_DELETING_STR
AS51:	DC.L TXT_MOVING,TXT_MOVING_STR
AS52:	DC.L TXT_SNAPSHOTWINDOW,TXT_SNAPSHOTWINDOW_STR
AS53:	DC.L TXT_YESALLNONENO,TXT_YESALLNONENO_STR
AS54:	DC.L TXT_HASICON,TXT_HASICON_STR
AS55:	DC.L ERR_NOCOPY,ERR_NOCOPY_STR
AS56:	DC.L ERR_NODEL,ERR_NODEL_STR
AS57:	DC.L ERR_NOMOVE,ERR_NOMOVE_STR
AS58:	DC.L TXT_ENTPAT,TXT_ENTPAT_STR
AS59:	DC.L TXT_NEWFILE,TXT_NEWFILE_STR
AS60:	DC.L TXT_OLDFILE,TXT_OLDFILE_STR
AS61:	DC.L TXT_MOVEAS,TXT_MOVEAS_STR
AS62:	DC.L TXT_DATESTRING,TXT_DATESTRING_STR
AS63:	DC.L TXT_DISPLAYTIME,TXT_DISPLAYTIME_STR
AS64:	DC.L TXT_BUTTABORT,TXT_BUTTABORT_STR
AS65:	DC.L TXT_DRAGBAR,TXT_DRAGBAR_STR
AS66:	DC.L TXT_TOOLBAR,TXT_TOOLBAR_STR
AS67:	DC.L TXT_VISIBLE,TXT_VISIBLE_STR
AS68:	DC.L TXT_BYTESSEL,TXT_BYTESSEL_STR
AS69:	DC.L TXT_CHECKING,TXT_CHECKING_STR
AS70:	DC.L TXT_DDSELECTED,TXT_DDSELECTED_STR
AS71:	DC.L TXT_NOTENOUGHSPACE,TXT_NOTENOUGHSPACE_STR
AS72:	DC.L TXT_CHECKFIT,TXT_CHECKFIT_STR
AS73:	DC.L TXT_DELETEICONS,TXT_DELETEICONS_STR
AS74:	DC.L TXT_GENERAL,TXT_GENERAL_STR
AS75:	DC.L TXT_HIGHDIRS,TXT_HIGHDIRS_STR
AS76:	DC.L TXT_ICONS,TXT_ICONS_STR
AS77:	DC.L TXT_LISTERS,TXT_LISTERS_STR
AS78:	DC.L TXT_SHOWIMAGES,TXT_SHOWIMAGES_STR
AS79:	DC.L TXT_USED,TXT_USED_STR
AS80:	DC.L TXT_BUTTPARENT,TXT_BUTTPARENT_STR
AS81:	DC.L TXT_NAME,TXT_NAME_STR
AS82:	DC.L TXT_SIZE,TXT_SIZE_STR
AS83:	DC.L TXT_DATE,TXT_DATE_STR
AS84:	DC.L TXT_BITS,TXT_BITS_STR
AS85:	DC.L TXT_BUTTDIR,TXT_BUTTDIR_STR
AS86:	DC.L TXT_BUTTDIR2,TXT_BUTTDIR2_STR
AS87:	DC.L TXT_COPY,TXT_COPY_STR
AS88:	DC.L TXT_CUT,TXT_CUT_STR
AS89:	DC.L TXT_EDIT,TXT_EDIT_STR
AS90:	DC.L TXT_PASTE,TXT_PASTE_STR
AS91:	DC.L TXT_PATHNOTIFY,TXT_PATHNOTIFY_STR
AS92:	DC.L TXT_SEARCH,TXT_SEARCH_STR
AS93:	DC.L TXT_SELALL,TXT_SELALL_STR
AS94:	DC.L TXT_SELNONE,TXT_SELNONE_STR
AS95:	DC.L TXT_SELTOGGLE,TXT_SELTOGGLE_STR
AS96:	DC.L TXT_SELTYPE,TXT_SELTYPE_STR
AS97:	DC.L TXT_SELPATTERN,TXT_SELPATTERN_STR
AS98:	DC.L TXT_DELETE,TXT_DELETE_STR
AS99:	DC.L TXT_COPYAS,TXT_COPYAS_STR
AS100:	DC.L TXT_FILE,TXT_FILE_STR
AS101:	DC.L TXT_MOVE,TXT_MOVE_STR
AS102:	DC.L TXT_PACK,TXT_PACK_STR
AS103:	DC.L TXT_BUTTREFRESH,TXT_BUTTREFRESH_STR
AS104:	DC.L TXT_CREATEARCHIVE,TXT_CREATEARCHIVE_STR
AS105:	DC.L TXT_CREATESUBDIR,TXT_CREATESUBDIR_STR
AS106:	DC.L TXT_DELOKSINGLE,TXT_DELOKSINGLE_STR
AS107:	DC.L TXT_GENERIC,TXT_GENERIC_STR
AS108:	DC.L TXT_BUTTACTIVATE,TXT_BUTTACTIVATE_STR
AS109:	DC.L TXT_BUTTDEACTIVATE,TXT_BUTTDEACTIVATE_STR
AS110:	DC.L MSG_COMMENT,MSG_COMMENT_STR
AS111:	DC.L MSG_ARCHIVE,MSG_ARCHIVE_STR
AS112:	DC.L MSG_EXECUTABLE,MSG_EXECUTABLE_STR
AS113:	DC.L MSG_OPENWINDOW,MSG_OPENWINDOW_STR
AS114:	DC.L MSG_READABLE,MSG_READABLE_STR
AS115:	DC.L MSG_ROOTDIR,MSG_ROOTDIR_STR
AS116:	DC.L MSG_SCRIPT,MSG_SCRIPT_STR
AS117:	DC.L MSG_VOLUMES,MSG_VOLUMES_STR
AS118:	DC.L MSG_WRITABLE,MSG_WRITABLE_STR
AS119:	DC.L MSG_DELETABLE,MSG_DELETABLE_STR
AS120:	DC.L MSG_COMMENT8,MSG_COMMENT8_STR
AS121:	DC.L MSG_DATE8,MSG_DATE8_STR
AS122:	DC.L MSG_DATENOTVALID,MSG_DATENOTVALID_STR
AS123:	DC.L MSG_FILEALREADYEXISTS,MSG_FILEALREADYEXISTS_STR
AS124:	DC.L MSG_NAME8,MSG_NAME8_STR
AS125:	DC.L MSG_PROTECTION8,MSG_PROTECTION8_STR
AS126:	DC.L MSG_CANCEL1,MSG_CANCEL1_STR
AS127:	DC.L MSG_OK1,MSG_OK1_STR
AS128:	DC.L MSG_NOTRASHCANAVAILABLE,MSG_NOTRASHCANAVAILABLE_STR
AS129:	DC.L MSG_BUTTFUELGAUGE,MSG_BUTTFUELGAUGE_STR
AS130:	DC.L MSG_COUNTINGFILES,MSG_COUNTINGFILES_STR
AS131:	DC.L TXT_DELOKTRASH,TXT_DELOKTRASH_STR
AS132:	DC.L TXT_DELOKSINGLETRASH,TXT_DELOKSINGLETRASH_STR
AS133:	DC.L MSG_DEPROTECTFILE,MSG_DEPROTECTFILE_STR
AS134:	DC.L ERR_NOMKDIR,ERR_NOMKDIR_STR
AS135:	DC.L MSG_VERSION,MSG_VERSION_STR
AS136:	DC.L MSG_NOTAVAILABLE,MSG_NOTAVAILABLE_STR
AS137:	DC.L MSG_VERSION8,MSG_VERSION8_STR
AS138:	DC.L MSG_COPYANDDELETE,MSG_COPYANDDELETE_STR
AS139:	DC.L MSG_PULLDOWNMENU,MSG_PULLDOWNMENU_STR
AS140:	DC.L MSG_REPLACEVERSION,MSG_REPLACEVERSION_STR
AS141:	DC.L MSG_SAVE1,MSG_SAVE1_STR
AS142:	DC.L MSG_SHOWVERSION,MSG_SHOWVERSION_STR
AS143:	DC.L MSG_COUNTFILES,MSG_COUNTFILES_STR
AS144:	DC.L MSG_CREATE1,MSG_CREATE1_STR
AS145:	DC.L MSG_ICON,MSG_ICON_STR
AS146:	DC.L MSG_NAMEOFDIR8,MSG_NAMEOFDIR8_STR
AS147:	DC.L MSG_PLEASEENTERDIRNAME,MSG_PLEASEENTERDIRNAME_STR
AS148:	DC.L MSG_ASSIGNTITLE,MSG_ASSIGNTITLE_STR
AS149:	DC.L MSG_COPYTO,MSG_COPYTO_STR
AS150:	DC.L MSG_ERR_ASSIGN,MSG_ERR_ASSIGN_STR
AS151:	DC.L MSG_OPENWITH,MSG_OPENWITH_STR
AS152:	DC.L MSG_PATHS,MSG_PATHS_STR
AS153:	DC.L MSG_VISITEDPATHS,MSG_VISITEDPATHS_STR
AS154:	DC.L MSG_ASSIGNEXISTS,MSG_ASSIGNEXISTS_STR
AS155:	DC.L MSG_ASSIGNMAKE,MSG_ASSIGNMAKE_STR
AS156:	DC.L MSG_ASSIGNREPLACEADD,MSG_ASSIGNREPLACEADD_STR
AS157:	DC.L MSG_ASSIGNREMOVE,MSG_ASSIGNREMOVE_STR
AS158:	DC.L MSG_ASSIGNWANTREMOVE,MSG_ASSIGNWANTREMOVE_STR
AS159:	DC.L MSG_CLOSEWINDOW,MSG_CLOSEWINDOW_STR
AS160:	DC.L MSG_CONFIRMCHECKSIZE,MSG_CONFIRMCHECKSIZE_STR
AS161:	DC.L MSG_DDIRSDFILES,MSG_DDIRSDFILES_STR
AS162:	DC.L MSG_NORENAME,MSG_NORENAME_STR
AS163:	DC.L ERR_WRONGPREFS,ERR_WRONGPREFS_STR
AS164:	DC.L MSG_CONFIRMDELETE,MSG_CONFIRMDELETE_STR
AS165:	DC.L MSG_TOOLS,MSG_TOOLS_STR
AS166:	DC.L MSG_NOCOPYTOSUBDIR,MSG_NOCOPYTOSUBDIR_STR

	ENDC ; CATCOMP_ARRAY


;-----------------------------------------------------------------------------


	IFD CATCOMP_BLOCK

	XDEF CatCompBlock
CatCompBlock:
	XDEF _CatCompBlock
_CatCompBlock:
	DC.L $110
	DC.W $6
	DC.B 'Help',$00,$00
	DC.L $111
	DC.W $8
	DC.B 'Iconify',$00
	DC.L $112
	DC.W $8
	DC.B 'Project',$00
	DC.L $113
	DC.W $6
	DC.B 'Quit',$00,$00
	DC.L $114
	DC.W $C
	DC.B 'Preferences',$00
	DC.L $115
	DC.W $6
	DC.B 'About',$00
	DC.L $117
	DC.W $2C
	DC.B 'Library not found.',10,'Check the requirements.',$00,$00
	DC.L $118
	DC.W $C
	DC.B 'Information',$00
	DC.L $119
	DC.W $D2
	DC.B '%s',10,10,'© 2003 by Martin R. Elsner & Salim Gasmi',10,10,'You can contact the auth'
	DC.B 'or at :',10,10,'Martin R. Elsner',10,'Muesener Strasse 46',10,'57223 Kreuztal',10,'Germany',10,10
	DC.B 'Email: classaction@martin-elsner.de ',10,'Web: http://www.martin-elsner.de',$00
	DC.L $11A
	DC.W $10
	DC.B 'Are you sure ?',$00,$00
	DC.L $11B
	DC.W $A
	DC.B 'Directory',$00
	DC.L $11E
	DC.W $26
	DC.B 'Not Enough Memory ',10,10,'to load the file',$00,$00
	DC.L $11F
	DC.W $8
	DC.B 'Unknown',$00
	DC.L $120
	DC.W $1C
	DC.B 'Syntax Error in REQ command',$00
	DC.L $121
	DC.W $8
	DC.B 'Yes|No',$00,$00
	DC.L $122
	DC.W $1E
	DC.B 'Syntax error in SURE command',$00,$00
	DC.L $123
	DC.W $8
	DC.B 'Assign',$00,$00
	DC.L $124
	DC.W $8
	DC.B 'Copy As',$00
	DC.L $125
	DC.W $8
	DC.B 'Drawer',$00,$00
	DC.L $126
	DC.W $8
	DC.B 'Volume',$00,$00
	DC.L $127
	DC.W $6
	DC.B 'Okay',$00,$00
	DC.L $128
	DC.W $8
	DC.B 'Cancel',$00,$00
	DC.L $129
	DC.W $34
	DC.B 'Do you really want to delete the entries %s, ... ?',$00,$00
	DC.L $12A
	DC.W $16
	DC.B 'Create new directory',$00,$00
	DC.L $12B
	DC.W $18
	DC.B 'Config file not found.',$00,$00
	DC.L $12C
	DC.W $20
	DC.B 'Your config file is corrupted.',$00,$00
	DC.L $12D
	DC.W $3A
	DC.B 'Your config file is not a valid',10,'ClassAction config file.',$00,$00
	DC.L $12F
	DC.W $22
	DC.B 'An unspecified error has occured.',$00
	DC.L $130
	DC.W $12
	DC.B 'There is no icon!',$00
	DC.L $131
	DC.W $1A
	DC.B 'This path does not exist!',$00
	DC.L $132
	DC.W $10
	DC.B 'File not found.',$00
	DC.L $133
	DC.W $24
	DC.B 'The ARexx port could not be opened.',$00
	DC.L $134
	DC.W $52
	DC.B 'Xfdmaster.library not found !!',10,'The autodecrunching function',10,'will be de'
	DC.B 'activated.',$00,$00
	DC.L $135
	DC.W $E
	DC.B 'Not crunched.',$00
	DC.L $136
	DC.W $12
	DC.B 'Not a data file.',$00,$00
	DC.L $137
	DC.W $10
	DC.B 'Not decrunched.',$00
	DC.L $139
	DC.W $8
	DC.B 'Rename',$00,$00
	DC.L $13B
	DC.W $18
	DC.B 'Do you want to replace',$00,$00
	DC.L $13D
	DC.W $10
	DC.B 'Confirm replace',$00
	DC.L $13E
	DC.W $C
	DC.B 'Copy Icons',$00,$00
	DC.L $13F
	DC.W $E
	DC.B 'Create Icons',$00,$00
	DC.L $140
	DC.W $E
	DC.B 'Display .info',$00
	DC.L $141
	DC.W $A
	DC.B 'Settings',$00,$00
	DC.L $142
	DC.W $14
	DC.B 'Show drawers first',$00,$00
	DC.L $14F
	DC.W $12
	DC.B 'Show all devices',$00,$00
	DC.L $150
	DC.W $14
	DC.B 'Show the given path',$00
	DC.L $151
	DC.W $18
	DC.B 'Create a new directory',$00,$00
	DC.L $153
	DC.W $18
	DC.B 'Enter a path to list it',$00
	DC.L $159
	DC.W $C
	DC.B 'ClassAction',$00
	DC.L $15A
	DC.W $8
	DC.B 'Copying',$00
	DC.L $15B
	DC.W $A
	DC.B 'Deleting',$00,$00
	DC.L $15C
	DC.W $8
	DC.B 'Moving',$00,$00
	DC.L $15E
	DC.W $10
	DC.B 'Snapshot Window',$00
	DC.L $15F
	DC.W $10
	DC.B 'Yes|All|None|No',$00
	DC.L $161
	DC.W $16
	DC.B 'has already an icon!',$00,$00
	DC.L $164
	DC.W $14
	DC.B 'Could not copy %s !',$00
	DC.L $165
	DC.W $16
	DC.B 'Could not delete %s !',$00
	DC.L $166
	DC.W $14
	DC.B 'Could not move %s !',$00
	DC.L $167
	DC.W $E
	DC.B 'Enter Pattern',$00
	DC.L $169
	DC.W $A
	DC.B 'New file:',$00
	DC.L $16A
	DC.W $A
	DC.B 'Old file:',$00
	DC.L $16B
	DC.W $8
	DC.B 'Move As',$00
	DC.L $16C
	DC.W $E
	DC.B 'Date as text',$00,$00
	DC.L $16D
	DC.W $E
	DC.B 'Display time',$00,$00
	DC.L $170
	DC.W $1A
	DC.B 'Abort the current process',$00
	DC.L $171
	DC.W $8
	DC.B 'Dragbar',$00
	DC.L $172
	DC.W $8
	DC.B 'Toolbar',$00
	DC.L $173
	DC.W $8
	DC.B 'Visible',$00
	DC.L $175
	DC.W $12
	DC.B '%s bytes selected',$00
	DC.L $176
	DC.W $A
	DC.B 'Checking',$00,$00
	DC.L $177
	DC.W $1C
	DC.B '%d selected / %d available',$00,$00
	DC.L $178
	DC.W $12
	DC.B 'Not enough space!',$00
	DC.L $181
	DC.W $C
	DC.B 'Check space',$00
	DC.L $182
	DC.W $E
	DC.B 'Delete icons',$00,$00
	DC.L $183
	DC.W $8
	DC.B 'General',$00
	DC.L $184
	DC.W $10
	DC.B 'Highlight dirs',$00,$00
	DC.L $185
	DC.W $6
	DC.B 'Icons',$00
	DC.L $186
	DC.W $8
	DC.B 'Listers',$00
	DC.L $187
	DC.W $C
	DC.B 'Show images',$00
	DC.L $188
	DC.W $6
	DC.B 'used',$00,$00
	DC.L $189
	DC.W $1C
	DC.B 'Go to the parent directory',$00,$00
	DC.L $18C
	DC.W $6
	DC.B 'Name',$00,$00
	DC.L $18D
	DC.W $6
	DC.B 'Size',$00,$00
	DC.L $18E
	DC.W $6
	DC.B 'Date',$00,$00
	DC.L $18F
	DC.W $6
	DC.B 'Bits',$00,$00
	DC.L $190
	DC.W $8
	DC.B 'Source',$00,$00
	DC.L $191
	DC.W $C
	DC.B 'Destination',$00
	DC.L $192
	DC.W $6
	DC.B 'Copy',$00,$00
	DC.L $193
	DC.W $4
	DC.B 'Cut',$00
	DC.L $194
	DC.W $6
	DC.B 'Edit',$00,$00
	DC.L $195
	DC.W $6
	DC.B 'Paste',$00
	DC.L $196
	DC.W $12
	DC.B 'Update on changes',$00
	DC.L $197
	DC.W $8
	DC.B 'Search',$00,$00
	DC.L $198
	DC.W $C
	DC.B 'Select all',$00,$00
	DC.L $199
	DC.W $10
	DC.B 'Select nothing',$00,$00
	DC.L $19A
	DC.W $12
	DC.B 'Toggle selection',$00,$00
	DC.L $19B
	DC.W $12
	DC.B 'Select same type',$00,$00
	DC.L $19C
	DC.W $10
	DC.B 'Select pattern',$00,$00
	DC.L $19D
	DC.W $8
	DC.B 'Delete',$00,$00
	DC.L $19E
	DC.W $8
	DC.B 'Copy as',$00
	DC.L $19F
	DC.W $6
	DC.B 'File',$00,$00
	DC.L $1A0
	DC.W $6
	DC.B 'Move',$00,$00
	DC.L $1A1
	DC.W $6
	DC.B 'Pack',$00,$00
	DC.L $1A2
	DC.W $14
	DC.B 'Refresh this lister',$00
	DC.L $1A3
	DC.W $10
	DC.B 'Create archive',$00,$00
	DC.L $1A4
	DC.W $14
	DC.B 'Create subdirectory',$00
	DC.L $1A5
	DC.W $2C
	DC.B 'Do you really want to delete the entry %s ?',$00
	DC.L $1A6
	DC.W $8
	DC.B 'Generic',$00
	DC.L $1A7
	DC.W $10
	DC.B 'Activate lister',$00
	DC.L $1A8
	DC.W $12
	DC.B 'Deactivate lister',$00
	DC.L $1AB
	DC.W $8
	DC.B 'Comment',$00
	DC.L $1AC
	DC.W $8
	DC.B 'Archive',$00
	DC.L $1AE
	DC.W $C
	DC.B 'Executable',$00,$00
	DC.L $1AF
	DC.W $C
	DC.B 'Open window',$00
	DC.L $1B0
	DC.W $A
	DC.B 'Readable',$00,$00
	DC.L $1B1
	DC.W $10
	DC.B 'Root directory',$00,$00
	DC.L $1B2
	DC.W $8
	DC.B 'Script',$00,$00
	DC.L $1B3
	DC.W $8
	DC.B 'Volumes',$00
	DC.L $1B4
	DC.W $A
	DC.B 'Writable',$00,$00
	DC.L $1B5
	DC.W $A
	DC.B 'Deletable',$00
	DC.L $1B6
	DC.W $A
	DC.B 'Comment:',$00,$00
	DC.L $1B7
	DC.W $6
	DC.B 'Date:',$00
	DC.L $1B8
	DC.W $18
	DC.B 'The date is not valid !',$00
	DC.L $1B9
	DC.W $1C
	DC.B 'This file already exists !',$00,$00
	DC.L $1BA
	DC.W $6
	DC.B 'Name:',$00
	DC.L $1BB
	DC.W $C
	DC.B 'Protection:',$00
	DC.L $1BC
	DC.W $8
	DC.B '_Cancel',$00
	DC.L $1BD
	DC.W $4
	DC.B '_Ok',$00
	DC.L $1BE
	DC.W $18
	DC.B 'No trashcan available !',$00
	DC.L $1C0
	DC.W $26
	DC.B 'Click here to adjust the browser size',$00
	DC.L $1C1
	DC.W $14
	DC.B 'Counting Files ...',$00,$00
	DC.L $1C2
	DC.W $44
	DC.B 'Do you really want to move the entries %s, ... into the trashcan ?',$00,$00
	DC.L $1C3
	DC.W $3C
	DC.B 'Do you really want to move the entry %s into the trashcan ?',$00
	DC.L $1C4
	DC.W $4E
	DC.B 'The file %s is write protected.',10,' Shall I remove the protection for thi'
	DC.B 's file?',$00
	DC.L $1C5
	DC.W $20
	DC.B 'Could not create directory %s !',$00
	DC.L $1C6
	DC.W $8
	DC.B 'Version',$00
	DC.L $1C7
	DC.W $E
	DC.B 'not available',$00
	DC.L $1C8
	DC.W $A
	DC.B 'Version:',$00,$00
	DC.L $1C9
	DC.W $10
	DC.B 'Copy and delete',$00
	DC.L $1CA
	DC.W $E
	DC.B 'Pulldown menu',$00
	DC.L $1CB
	DC.W $18
	DC.B 'Replace older versions',$00,$00
	DC.L $1CC
	DC.W $6
	DC.B '_Save',$00
	DC.L $1CD
	DC.W $E
	DC.B 'Show version',$00,$00
	DC.L $1CE
	DC.W $C
	DC.B 'Count Files',$00
	DC.L $1D0
	DC.W $8
	DC.B '_Create',$00
	DC.L $1D1
	DC.W $6
	DC.B 'Icon',$00,$00
	DC.L $1D2
	DC.W $18
	DC.B 'Name of the directory:',$00,$00
	DC.L $1D3
	DC.W $2C
	DC.B 'Please enter the name of the new directory.',$00
	DC.L $1D6
	DC.W $1C
	DC.B 'Please enter assign title:',$00,$00
	DC.L $1D7
	DC.W $8
	DC.B 'Copy to',$00
	DC.L $1D8
	DC.W $4A
	DC.B 'Assign could not be created. Please check if this assign already exist'
	DC.B 's.',$00,$00
	DC.L $1D9
	DC.W $A
	DC.B 'Open with',$00
	DC.L $1DA
	DC.W $6
	DC.B 'Paths',$00
	DC.L $1DB
	DC.W $E
	DC.B 'Visited paths',$00
	DC.L $1DC
	DC.W $1C
	DC.B 'This assign already exists.',$00
	DC.L $1DD
	DC.W $C
	DC.B 'Make assign',$00
	DC.L $1DE
	DC.W $14
	DC.B 'Replace|Add|Cancel',$00,$00
	DC.L $1DF
	DC.W $E
	DC.B 'Remove assign',$00
	DC.L $1E0
	DC.W $2A
	DC.B 'Do you really want to remove this assign?',$00
	DC.L $1E1
	DC.W $2A
	DC.B 'Please close all windows on this screen.',$00,$00
	DC.L $1E2
	DC.W $44
	DC.B 'The volume reports 0 bytes of free space. Do you want to continue?',$00,$00
	DC.L $1E3
	DC.W $20
	DC.B '%d/%d directories, %d/%d files',$00,$00
	DC.L $1E4
	DC.W $16
	DC.B 'Could not rename %s !',$00
	DC.L $1E5
	DC.W $AA
	DC.B 'This is an old preference file.',10,'Please start ClassActionPrefs and save'
	DC.B ' your preferences.',10,'Check if you are using the correct version of Class'
	DC.B 'Action and ClassActionPrefs.',$00,$00
	DC.L $1E6
	DC.W $10
	DC.B 'Confirm delete',$00,$00
	DC.L $1E7
	DC.W $6
	DC.B 'Tools',$00
	DC.L $1E8
	DC.W $36
	DC.B 'It',39,'s not allowed to copy directories into any subdir!',$00

	ENDC ; CATCOMP_BLOCK


;-----------------------------------------------------------------------------


   STRUCTURE LocaleInfo,0
	APTR li_LocaleBase
	APTR li_Catalog
   LABEL LocaleInfo_SIZEOF

	IFD CATCOMP_CODE

	XREF      _LVOGetCatalogStr
	XDEF      _GetString
	XDEF      GetString
GetString:
_GetString:
	lea       CatCompBlock(pc),a1
	bra.s     2$
1$: move.w  (a1)+,d1
	add.w     d1,a1
2$: cmp.l   (a1)+,d0
	bne.s     1$
	addq.l    #2,a1
	move.l    (a0)+,d1
	bne.s     3$
	move.l    a1,d0
	rts
3$: move.l  a6,-(sp)
	move.l    d1,a6
	move.l    (a0),a0
	jsr       _LVOGetCatalogStr(a6)
	move.l    (sp)+,a6
	rts
	END

	ENDC ; CATCOMP_CODE


;-----------------------------------------------------------------------------


	ENDC ; CLASSACTIONCD_I
