	IFND CLASSACTIONPREFSCD_I
CLASSACTIONPREFSCD_I	SET	1


;-----------------------------------------------------------------------------


* This file was created automatically by CatComp.
* Do NOT edit by hand!
*


	IFND EXEC_TYPES_I
	INCLUDE 'exec/types.i'
	ENDC

	IFD CATCOMP_ARRAY
CATCOMP_NUMBERS SET 1
CATCOMP_STRINGS SET 1
	ENDC

	IFD CATCOMP_CODE
CATCOMP_BLOCK SET 1
	ENDC


;-----------------------------------------------------------------------------


	IFD CATCOMP_NUMBERS

	XDEF TXT_CLASSNAME
TXT_CLASSNAME EQU 259
	XDEF TXT_MATCHNAME
TXT_MATCHNAME EQU 260
	XDEF TXT_OFFSET1
TXT_OFFSET1 EQU 261
	XDEF TXT_OFFSET2
TXT_OFFSET2 EQU 262
	XDEF TXT_OFFSET3
TXT_OFFSET3 EQU 263
	XDEF TXT_OFFSET4
TXT_OFFSET4 EQU 264
	XDEF TXT_OFFSET5
TXT_OFFSET5 EQU 265
	XDEF TXT_BUTTLST1
TXT_BUTTLST1 EQU 301
	XDEF TXT_BUTTCLASS
TXT_BUTTCLASS EQU 302
	XDEF TXT_BUTTMATCH
TXT_BUTTMATCH EQU 303
	XDEF TXT_BUTTCHOFF
TXT_BUTTCHOFF EQU 304
	XDEF TXT_BUTTOFFSET
TXT_BUTTOFFSET EQU 305
	XDEF TXT_BUTTADD
TXT_BUTTADD EQU 306
	XDEF TXT_BUTTREMOVE
TXT_BUTTREMOVE EQU 307
	XDEF TXT_BUTTLST2
TXT_BUTTLST2 EQU 309
	XDEF TXT_BUTTANAME
TXT_BUTTANAME EQU 310
	XDEF TXT_BUTTUP
TXT_BUTTUP EQU 314
	XDEF TXT_BUTTDOWN
TXT_BUTTDOWN EQU 315
	XDEF TXT_BUTTADD2
TXT_BUTTADD2 EQU 318
	XDEF TXT_BUTTREMOVE2
TXT_BUTTREMOVE2 EQU 319
	XDEF TXT_ABOUT
TXT_ABOUT EQU 323
	XDEF TXT_PROJECT
TXT_PROJECT EQU 324
	XDEF MEN_QUIT
MEN_QUIT EQU 325
	XDEF ERR_GENERAL
ERR_GENERAL EQU 327
	XDEF ERR_NOCONFIG
ERR_NOCONFIG EQU 328
	XDEF ERR_NOICON
ERR_NOICON EQU 329
	XDEF ERR_NOLIB
ERR_NOLIB EQU 330
	XDEF TXT_DELACTION
TXT_DELACTION EQU 331
	XDEF TXT_DELCLASS
TXT_DELCLASS EQU 332
	XDEF TXT_NEWACTION
TXT_NEWACTION EQU 333
	XDEF TXT_NEWCLASS
TXT_NEWCLASS EQU 334
	XDEF TXT_NOACT
TXT_NOACT EQU 335
	XDEF TXT_INFORMATION
TXT_INFORMATION EQU 336
	XDEF TXT_OK
TXT_OK EQU 337
	XDEF TXT_YESNO
TXT_YESNO EQU 338
	XDEF ERR_CONFIGNOTVALID
ERR_CONFIGNOTVALID EQU 339
	XDEF ERR_GENERICNOTVALID
ERR_GENERICNOTVALID EQU 340
	XDEF TXT_GENERIC
TXT_GENERIC EQU 341
	XDEF TXT_UNKNOWN
TXT_UNKNOWN EQU 342
	XDEF TXT_DIRECTORY
TXT_DIRECTORY EQU 343
	XDEF ERR_DIRNOTVALID
ERR_DIRNOTVALID EQU 344
	XDEF ERR_CONFIGCORRUPT
ERR_CONFIGCORRUPT EQU 345
	XDEF TXT_LCHOOSE
TXT_LCHOOSE EQU 346
	XDEF TXT_LCOMP
TXT_LCOMP EQU 347
	XDEF TXT_LPREP
TXT_LPREP EQU 348
	XDEF TXT_LPROG
TXT_LPROG EQU 349
	XDEF TXT_LEARN
TXT_LEARN EQU 350
	XDEF TXT_ACCEPT
TXT_ACCEPT EQU 351
	XDEF TXT_BUTTLACCEPT
TXT_BUTTLACCEPT EQU 352
	XDEF TXT_BUTTLCANCEL
TXT_BUTTLCANCEL EQU 353
	XDEF TXT_PROG
TXT_PROG EQU 354
	XDEF TXT_LMEMORY
TXT_LMEMORY EQU 355
	XDEF TXT_LNEED
TXT_LNEED EQU 356
	XDEF TXT_LNOTHING
TXT_LNOTHING EQU 357
	XDEF TXT_COPYRIGHT
TXT_COPYRIGHT EQU 360
	XDEF TXT_OPTIONS
TXT_OPTIONS EQU 362
	XDEF TXT_COMMANDS
TXT_COMMANDS EQU 363
	XDEF TXT_CLASSES
TXT_CLASSES EQU 364
	XDEF TXT_SAVE
TXT_SAVE EQU 365
	XDEF TXT_BUTTSAVE
TXT_BUTTSAVE EQU 366
	XDEF TXT_USE
TXT_USE EQU 367
	XDEF TXT_BUTTUSE
TXT_BUTTUSE EQU 368
	XDEF TXT_CANCEL
TXT_CANCEL EQU 369
	XDEF TXT_BUTTCANCEL
TXT_BUTTCANCEL EQU 370
	XDEF TXT_ISSURE
TXT_ISSURE EQU 371
	XDEF TXT_ACTIKEY
TXT_ACTIKEY EQU 398
	XDEF TXT_SELRAWKEY
TXT_SELRAWKEY EQU 399
	XDEF TXT_NAMEE
TXT_NAMEE EQU 404
	XDEF TXT_ICON
TXT_ICON EQU 405
	XDEF TXT_ADD
TXT_ADD EQU 406
	XDEF TXT_REMOVE
TXT_REMOVE EQU 407
	XDEF TXT_NAME
TXT_NAME EQU 424
	XDEF TXT_BUTTCOMM
TXT_BUTTCOMM EQU 426
	XDEF TXT_REQPF2
TXT_REQPF2 EQU 427
	XDEF TXT_REQS2
TXT_REQS2 EQU 428
	XDEF TXT_REQB2
TXT_REQB2 EQU 429
	XDEF TXT_REQX2
TXT_REQX2 EQU 430
	XDEF TXT_SRC
TXT_SRC EQU 431
	XDEF TXT_SRCS
TXT_SRCS EQU 432
	XDEF TXT_DST
TXT_DST EQU 433
	XDEF TXT_DSTS
TXT_DSTS EQU 434
	XDEF TXT_REQF
TXT_REQF EQU 435
	XDEF TXT_REQD
TXT_REQD EQU 436
	XDEF TXT_REQT
TXT_REQT EQU 437
	XDEF TXT_SURE
TXT_SURE EQU 438
	XDEF TXT_COMMAND
TXT_COMMAND EQU 443
	XDEF TXT_CLI
TXT_CLI EQU 444
	XDEF TXT_WB
TXT_WB EQU 445
	XDEF TXT_NOCLI
TXT_NOCLI EQU 446
	XDEF TXT_AREXX
TXT_AREXX EQU 447
	XDEF TXT_INTERNAL
TXT_INTERNAL EQU 448
	XDEF TXT_SPACE
TXT_SPACE EQU 449
	XDEF TXT_BUTTMODE
TXT_BUTTMODE EQU 450
	XDEF TXT_MODE
TXT_MODE EQU 451
	XDEF TXT_INTCOMMANDS
TXT_INTCOMMANDS EQU 452
	XDEF TXT_VARIABLES
TXT_VARIABLES EQU 453
	XDEF TXT_HELPE
TXT_HELPE EQU 454
	XDEF TXT_BUTTSTACK
TXT_BUTTSTACK EQU 456
	XDEF TXT_STACK
TXT_STACK EQU 457
	XDEF TXT_BUTTDELAY
TXT_BUTTDELAY EQU 458
	XDEF TXT_DELAY
TXT_DELAY EQU 459
	XDEF MSG_READSOURCE
MSG_READSOURCE EQU 460
	XDEF TXT_CHOOSEICON
TXT_CHOOSEICON EQU 474
	XDEF TXT_PRESSKEY
TXT_PRESSKEY EQU 475
	XDEF TXT_BUTTCOMMAND
TXT_BUTTCOMMAND EQU 488
	XDEF TXT_BUTTLOAD
TXT_BUTTLOAD EQU 489
	XDEF TXT_BUTTLCOM
TXT_BUTTLCOM EQU 493
	XDEF TXT_BUTTCUP
TXT_BUTTCUP EQU 494
	XDEF TXT_BUTTCDOWN
TXT_BUTTCDOWN EQU 495
	XDEF TXT_BUTTCADD
TXT_BUTTCADD EQU 496
	XDEF TXT_BUTTCREM
TXT_BUTTCREM EQU 497
	XDEF TXT_BUTTCNAME
TXT_BUTTCNAME EQU 498
	XDEF TXT_BUTTCHELP
TXT_BUTTCHELP EQU 499
	XDEF TXT_BUTTINT
TXT_BUTTINT EQU 500
	XDEF TXT_BUTTOPTIONS
TXT_BUTTOPTIONS EQU 502
	XDEF TXT_ICONS
TXT_ICONS EQU 503
	XDEF TXT_BUTTONS
TXT_BUTTONS EQU 505
	XDEF TXT_LISTERS
TXT_LISTERS EQU 506
	XDEF TXT_BUTTGTICON
TXT_BUTTGTICON EQU 507
	XDEF TXT_BUTTPREVIEW
TXT_BUTTPREVIEW EQU 508
	XDEF TXT_BUTTKEY
TXT_BUTTKEY EQU 509
	XDEF TXT_BUTTSTRKEY
TXT_BUTTSTRKEY EQU 510
	XDEF TXT_BUTTCHKEY
TXT_BUTTCHKEY EQU 511
	XDEF TXT_SHOWHELP
TXT_SHOWHELP EQU 512
	XDEF TXT_WINDOW
TXT_WINDOW EQU 515
	XDEF TXT_ACTIONS
TXT_ACTIONS EQU 517
	XDEF TXT_DISPINFO
TXT_DISPINFO EQU 524
	XDEF TXT_DISPTIME
TXT_DISPTIME EQU 525
	XDEF TXT_PARENT
TXT_PARENT EQU 529
	XDEF TXT_PATHS
TXT_PATHS EQU 530
	XDEF TXT_HEIGHT
TXT_HEIGHT EQU 531
	XDEF TXT_ICONSTART
TXT_ICONSTART EQU 532
	XDEF TXT_LEFTEDGE
TXT_LEFTEDGE EQU 533
	XDEF TXT_MUIQUIT
TXT_MUIQUIT EQU 534
	XDEF TXT_TOPEDGE
TXT_TOPEDGE EQU 535
	XDEF TXT_WIDTH
TXT_WIDTH EQU 536
	XDEF TXT_CONFIRMREPLACE
TXT_CONFIRMREPLACE EQU 537
	XDEF TXT_COPYICONS
TXT_COPYICONS EQU 538
	XDEF TXT_CREATEICONS
TXT_CREATEICONS EQU 539
	XDEF TXT_DATESTRING
TXT_DATESTRING EQU 540
	XDEF TXT_DRAWERSFIRST
TXT_DRAWERSFIRST EQU 541
	XDEF TXT_GENERAL
TXT_GENERAL EQU 542
	XDEF TXT_CLISIZE
TXT_CLISIZE EQU 543
	XDEF TXT_CHOOSEFILE
TXT_CHOOSEFILE EQU 545
	XDEF TXT_PATH
TXT_PATH EQU 547
	XDEF TXT_NOTAVAIL
TXT_NOTAVAIL EQU 548
	XDEF TXT_OPENPREFS
TXT_OPENPREFS EQU 549
	XDEF TXT_SAVEPREFS
TXT_SAVEPREFS EQU 552
	XDEF TXT_SMALLIM
TXT_SMALLIM EQU 555
	XDEF TXT_EDIT
TXT_EDIT EQU 556
	XDEF MEN_LASTSAVED
MEN_LASTSAVED EQU 557
	XDEF MEN_OPEN
MEN_OPEN EQU 558
	XDEF MEN_RESET
MEN_RESET EQU 559
	XDEF MEN_RESTORE
MEN_RESTORE EQU 560
	XDEF TXT_BOTTOMICONS
TXT_BOTTOMICONS EQU 562
	XDEF TXT_CHECKFIT
TXT_CHECKFIT EQU 564
	XDEF ERR_SAVEPREFS
ERR_SAVEPREFS EQU 565
	XDEF TXT_HIGHDIRS
TXT_HIGHDIRS EQU 566
	XDEF TXT_KEYCOM
TXT_KEYCOM EQU 568
	XDEF TXT_REPLACETOOLTYPES
TXT_REPLACETOOLTYPES EQU 569
	XDEF TXT_SHOWIM
TXT_SHOWIM EQU 570
	XDEF TXT_TOPICONS
TXT_TOPICONS EQU 571
	XDEF MEN_SAVEAS
MEN_SAVEAS EQU 573
	XDEF TXT_WHEREISCA
TXT_WHEREISCA EQU 574
	XDEF TXT_APPX
TXT_APPX EQU 575
	XDEF TXT_APPY
TXT_APPY EQU 576
	XDEF TXT_DSTSTARTPATH
TXT_DSTSTARTPATH EQU 577
	XDEF TXT_PUBLICSCREEN
TXT_PUBLICSCREEN EQU 578
	XDEF TXT_SRCSTARTPATH
TXT_SRCSTARTPATH EQU 579
	XDEF TXT_SHOWDEVS
TXT_SHOWDEVS EQU 580
	XDEF TXT_DELETEICONS
TXT_DELETEICONS EQU 581
	XDEF TXT_MAXPATHS
TXT_MAXPATHS EQU 583
	XDEF TXT_MAXTABS
TXT_MAXTABS EQU 584
	XDEF TXT_PATHNOTIFY
TXT_PATHNOTIFY EQU 585
	XDEF TXT_REFRESH
TXT_REFRESH EQU 586
	XDEF TXT_LISTERFONT
TXT_LISTERFONT EQU 587
	XDEF TXT_MENUFONT
TXT_MENUFONT EQU 588
	XDEF TXT_BACKGROUND
TXT_BACKGROUND EQU 589
	XDEF MSG_DELETEPROTECTED
MSG_DELETEPROTECTED EQU 590
	XDEF TXT_PATHMENU
TXT_PATHMENU EQU 591
	XDEF MSG_VERTICAL
MSG_VERTICAL EQU 592
	XDEF MEN_HELP
MEN_HELP EQU 593
	XDEF MSG_SUPPORTEDARCHIVES
MSG_SUPPORTEDARCHIVES EQU 594
	XDEF MSG_BUTTOPENICONS
MSG_BUTTOPENICONS EQU 595
	XDEF MSG_ASYNC
MSG_ASYNC EQU 599
	XDEF MSG_READDEST
MSG_READDEST EQU 600
	XDEF MSG_BUFFERSIZE
MSG_BUFFERSIZE EQU 602
	XDEF MSG_COPYANDDELETE
MSG_COPYANDDELETE EQU 603
	XDEF MSG_COUNTFILES
MSG_COUNTFILES EQU 604
	XDEF MSG_HIDEKEY
MSG_HIDEKEY EQU 605
	XDEF MEN_SHOWHELP
MEN_SHOWHELP EQU 606
	XDEF MSG_POPUPKEY
MSG_POPUPKEY EQU 607
	XDEF MSG_PULLDOWNMENU
MSG_PULLDOWNMENU EQU 608
	XDEF MSG_REPLACEVERSION
MSG_REPLACEVERSION EQU 609
	XDEF MSG_SHOWVERSION
MSG_SHOWVERSION EQU 610
	XDEF MSG_NAME
MSG_NAME EQU 611
	XDEF MSG_PATH
MSG_PATH EQU 612
	XDEF TXT_BUTTLPATHS
TXT_BUTTLPATHS EQU 613
	XDEF MSG_OPENWITH
MSG_OPENWITH EQU 614
	XDEF MSG_PATHLIST
MSG_PATHLIST EQU 615
	XDEF TXT_BUTTPUP
TXT_BUTTPUP EQU 616
	XDEF TXT_BUTTPDOWN
TXT_BUTTPDOWN EQU 617
	XDEF TXT_BUTTPADD
TXT_BUTTPADD EQU 618
	XDEF TXT_BUTTPREM
TXT_BUTTPREM EQU 619
	XDEF MSG_ENTERPATH
MSG_ENTERPATH EQU 620
	XDEF MSG_ENTERPATHTITLE
MSG_ENTERPATHTITLE EQU 621
	XDEF MSG_TABBUTTONSTRANSPARENT
MSG_TABBUTTONSTRANSPARENT EQU 622
	XDEF MSG_VOLUME
MSG_VOLUME EQU 623
	XDEF ERR_DELCLASS
ERR_DELCLASS EQU 624
	XDEF MSG_BUTTCLASSIMAGE
MSG_BUTTCLASSIMAGE EQU 625
	XDEF MSG_IMAGE
MSG_IMAGE EQU 626
	XDEF MSG_BUTTLOADIMAGE
MSG_BUTTLOADIMAGE EQU 627
	XDEF MSG_CLASSIMAGES
MSG_CLASSIMAGES EQU 628
	XDEF MSG_OWNSCREEN
MSG_OWNSCREEN EQU 629
	XDEF MSG_ARCHIVE
MSG_ARCHIVE EQU 630
	XDEF MSG_ONLYPATTERNS
MSG_ONLYPATTERNS EQU 631
	XDEF MSG_DUPLICATE
MSG_DUPLICATE EQU 634
	XDEF MSG_PASTE
MSG_PASTE EQU 635
	XDEF MSG_LEARN
MSG_LEARN EQU 636
	XDEF MSG_IMPORT
MSG_IMPORT EQU 637
	XDEF MSG_EXPORT
MSG_EXPORT EQU 638
	XDEF MSG_COPY
MSG_COPY EQU 639
	XDEF MSG_BLUE
MSG_BLUE EQU 640
	XDEF MSG_DATEFORMAT
MSG_DATEFORMAT EQU 641
	XDEF MSG_EXPORTCLASS
MSG_EXPORTCLASS EQU 642
	XDEF MSG_GREEN
MSG_GREEN EQU 643
	XDEF MSG_IMPORTCLASS
MSG_IMPORTCLASS EQU 644
	XDEF MSG_RED
MSG_RED EQU 645
	XDEF MSG_USEEXALL
MSG_USEEXALL EQU 646
	XDEF MSG_USEREACTIONREQUEST
MSG_USEREACTIONREQUEST EQU 647
	XDEF MSG_BUTTDIR
MSG_BUTTDIR EQU 648
	XDEF MSG_SOURCE
MSG_SOURCE EQU 649
	XDEF MSG_DESTINATION
MSG_DESTINATION EQU 650
	XDEF MSG_PROGDIR
MSG_PROGDIR EQU 651
	XDEF MSG_CD
MSG_CD EQU 652
	XDEF MSG_CONFIRMDELETE
MSG_CONFIRMDELETE EQU 653
	XDEF MSG_EXALLFILES
MSG_EXALLFILES EQU 654

	ENDC ; CATCOMP_NUMBERS


;-----------------------------------------------------------------------------


	IFD CATCOMP_STRINGS

	XDEF TXT_CLASSNAME_STR
TXT_CLASSNAME_STR: DC.B 'Class name',$00
	XDEF TXT_MATCHNAME_STR
TXT_MATCHNAME_STR: DC.B 'Pattern',$00
	XDEF TXT_OFFSET1_STR
TXT_OFFSET1_STR: DC.B 'Offset #1',$00
	XDEF TXT_OFFSET2_STR
TXT_OFFSET2_STR: DC.B 'Offset #2',$00
	XDEF TXT_OFFSET3_STR
TXT_OFFSET3_STR: DC.B 'Offset #3',$00
	XDEF TXT_OFFSET4_STR
TXT_OFFSET4_STR: DC.B 'Offset #4',$00
	XDEF TXT_OFFSET5_STR
TXT_OFFSET5_STR: DC.B 'Offset #5',$00
	XDEF TXT_BUTTLST1_STR
TXT_BUTTLST1_STR: DC.B 'List of defined classes',$00
	XDEF TXT_BUTTCLASS_STR
TXT_BUTTCLASS_STR: DC.B 'Name of the class',$00
	XDEF TXT_BUTTMATCH_STR
TXT_BUTTMATCH_STR: DC.B 'Pattern that must be matched',$00
	XDEF TXT_BUTTCHOFF_STR
TXT_BUTTCHOFF_STR: DC.B 'Select one of 6 Offsets',$00
	XDEF TXT_BUTTOFFSET_STR
TXT_BUTTOFFSET_STR: DC.B 'Enter the matching text',$00
	XDEF TXT_BUTTADD_STR
TXT_BUTTADD_STR: DC.B 'Add a new class',$00
	XDEF TXT_BUTTREMOVE_STR
TXT_BUTTREMOVE_STR: DC.B 'Remove this class',$00
	XDEF TXT_BUTTLST2_STR
TXT_BUTTLST2_STR: DC.B 'List of defined actions',$00
	XDEF TXT_BUTTANAME_STR
TXT_BUTTANAME_STR: DC.B 'The name of the action',$00
	XDEF TXT_BUTTUP_STR
TXT_BUTTUP_STR: DC.B 'Move this action up',$00
	XDEF TXT_BUTTDOWN_STR
TXT_BUTTDOWN_STR: DC.B 'Move this action down',$00
	XDEF TXT_BUTTADD2_STR
TXT_BUTTADD2_STR: DC.B 'Add a new action',$00
	XDEF TXT_BUTTREMOVE2_STR
TXT_BUTTREMOVE2_STR: DC.B 'Remove this action',$00
	XDEF TXT_ABOUT_STR
TXT_ABOUT_STR: DC.B 'About',$00
	XDEF TXT_PROJECT_STR
TXT_PROJECT_STR: DC.B 'Project',$00
	XDEF MEN_QUIT_STR
MEN_QUIT_STR: DC.B 'Q_Quit',$00
	XDEF ERR_GENERAL_STR
ERR_GENERAL_STR: DC.B 'An unspecified error has occured.',$00
	XDEF ERR_NOCONFIG_STR
ERR_NOCONFIG_STR: DC.B 'Config file not found.',$00
	XDEF ERR_NOICON_STR
ERR_NOICON_STR: DC.B 'There is no icon!',$00
	XDEF ERR_NOLIB_STR
ERR_NOLIB_STR: DC.B 'Library not found. Perhaps wrong OS.',$00
	XDEF TXT_DELACTION_STR
TXT_DELACTION_STR: DC.B 'Delete this action ?',$00
	XDEF TXT_DELCLASS_STR
TXT_DELCLASS_STR: DC.B 'Delete this class ?',$00
	XDEF TXT_NEWACTION_STR
TXT_NEWACTION_STR: DC.B '<New action #%d>',$00
	XDEF TXT_NEWCLASS_STR
TXT_NEWCLASS_STR: DC.B '<New class #%d>',$00
	XDEF TXT_NOACT_STR
TXT_NOACT_STR: DC.B 'No action',$00
	XDEF TXT_INFORMATION_STR
TXT_INFORMATION_STR: DC.B 'Information',$00
	XDEF TXT_OK_STR
TXT_OK_STR: DC.B 'Ok',$00
	XDEF TXT_YESNO_STR
TXT_YESNO_STR: DC.B 'Yes|No',$00
	XDEF ERR_CONFIGNOTVALID_STR
ERR_CONFIGNOTVALID_STR: DC.B 'Your config file',10,10,'is not a valid',10,10,'ClassAction config file',$00
	XDEF ERR_GENERICNOTVALID_STR
ERR_GENERICNOTVALID_STR: DC.B 'The generic file is not valid.',$00
	XDEF TXT_GENERIC_STR
TXT_GENERIC_STR: DC.B 'Generic actions',$00
	XDEF TXT_UNKNOWN_STR
TXT_UNKNOWN_STR: DC.B 'Unknown class',$00
	XDEF TXT_DIRECTORY_STR
TXT_DIRECTORY_STR: DC.B 'Directory',$00
	XDEF ERR_DIRNOTVALID_STR
ERR_DIRNOTVALID_STR: DC.B 'The dir file is not valid.',$00
	XDEF ERR_CONFIGCORRUPT_STR
ERR_CONFIGCORRUPT_STR: DC.B 'Your config file',10,10,'is corrupted.',$00
	XDEF TXT_LCHOOSE_STR
TXT_LCHOOSE_STR: DC.B 'Choose files to learn from.',$00
	XDEF TXT_LCOMP_STR
TXT_LCOMP_STR: DC.B 'Analysis complete.',$00
	XDEF TXT_LPREP_STR
TXT_LPREP_STR: DC.B 'Preprocessing ... please wait',$00
	XDEF TXT_LPROG_STR
TXT_LPROG_STR: DC.B 'Analysis in progress ...',$00
	XDEF TXT_LEARN_STR
TXT_LEARN_STR: DC.B 'Learn',$00
	XDEF TXT_ACCEPT_STR
TXT_ACCEPT_STR: DC.B 'Accept',$00
	XDEF TXT_BUTTLACCEPT_STR
TXT_BUTTLACCEPT_STR: DC.B 'Accept these offsets and strings',$00
	XDEF TXT_BUTTLCANCEL_STR
TXT_BUTTLCANCEL_STR: DC.B 'Cancel the learning process',$00
	XDEF TXT_PROG_STR
TXT_PROG_STR: DC.B 'ClassActionPrefs',$00
	XDEF TXT_LMEMORY_STR
TXT_LMEMORY_STR: DC.B 'Not enough memory for learning.',$00
	XDEF TXT_LNEED_STR
TXT_LNEED_STR: DC.B 'I need at leat 2 files for learning.',$00
	XDEF TXT_LNOTHING_STR
TXT_LNOTHING_STR: DC.B 'Nothing found.',$00
	XDEF TXT_COPYRIGHT_STR
TXT_COPYRIGHT_STR: DC.B '   %s',10,10,'© 2002 by Martin R. Elsner & Salim Gasmi',10,10,'You can contact me at'
	DC.B ' :',10,10,'Martin R. Elsner',10,'Muesener Strasse 46',10,'57223 Kreuztal',10,'Germany',10,10,'Email'
	DC.B ': email@martin-elsner.de',10,'Web: http://www.martin-elsner.de',$00
	XDEF TXT_OPTIONS_STR
TXT_OPTIONS_STR: DC.B 'Options',$00
	XDEF TXT_COMMANDS_STR
TXT_COMMANDS_STR: DC.B 'Commands',$00
	XDEF TXT_CLASSES_STR
TXT_CLASSES_STR: DC.B 'Classes',$00
	XDEF TXT_SAVE_STR
TXT_SAVE_STR: DC.B 'Save',$00
	XDEF TXT_BUTTSAVE_STR
TXT_BUTTSAVE_STR: DC.B 'Save the changes',$00
	XDEF TXT_USE_STR
TXT_USE_STR: DC.B 'Use',$00
	XDEF TXT_BUTTUSE_STR
TXT_BUTTUSE_STR: DC.B 'Use the changes without saving',$00
	XDEF TXT_CANCEL_STR
TXT_CANCEL_STR: DC.B 'Cancel',$00
	XDEF TXT_BUTTCANCEL_STR
TXT_BUTTCANCEL_STR: DC.B 'Quit without saving',$00
	XDEF TXT_ISSURE_STR
TXT_ISSURE_STR: DC.B 'Are you sure ?',$00
	XDEF TXT_ACTIKEY_STR
TXT_ACTIKEY_STR: DC.B 'Activation key',$00
	XDEF TXT_SELRAWKEY_STR
TXT_SELRAWKEY_STR: DC.B 'Select RAW key',$00
	XDEF TXT_NAMEE_STR
TXT_NAMEE_STR: DC.B 'Name:',$00
	XDEF TXT_ICON_STR
TXT_ICON_STR: DC.B 'Icon',$00
	XDEF TXT_ADD_STR
TXT_ADD_STR: DC.B 'Add',$00
	XDEF TXT_REMOVE_STR
TXT_REMOVE_STR: DC.B 'Remove',$00
	XDEF TXT_NAME_STR
TXT_NAME_STR: DC.B 'Name',$00
	XDEF TXT_BUTTCOMM_STR
TXT_BUTTCOMM_STR: DC.B 'Choose a variable',$00
	XDEF TXT_REQPF2_STR
TXT_REQPF2_STR: DC.B '[F] Path+Filename',$00
	XDEF TXT_REQS2_STR
TXT_REQS2_STR: DC.B '[S] Path+Filename without suffix',$00
	XDEF TXT_REQB2_STR
TXT_REQB2_STR: DC.B '[B] Filename',$00
	XDEF TXT_REQX2_STR
TXT_REQX2_STR: DC.B '[X] Filename without suffix',$00
	XDEF TXT_SRC_STR
TXT_SRC_STR: DC.B '[SRC] Path of source lister',$00
	XDEF TXT_SRCS_STR
TXT_SRCS_STR: DC.B '[SRCS] Path of source lister + ',39,'/',39,$00
	XDEF TXT_DST_STR
TXT_DST_STR: DC.B '[DST] Path of destination lister',$00
	XDEF TXT_DSTS_STR
TXT_DSTS_STR: DC.B '[DSTS] Path of destination lister + ',39,'/',39,$00
	XDEF TXT_REQF_STR
TXT_REQF_STR: DC.B '[REQF:...] Request a file',$00
	XDEF TXT_REQD_STR
TXT_REQD_STR: DC.B '[REQD:...] Request a directory',$00
	XDEF TXT_REQT_STR
TXT_REQT_STR: DC.B '[REQT:...] Request a text',$00
	XDEF TXT_SURE_STR
TXT_SURE_STR: DC.B '[SURE:...] Confirm a command',$00
	XDEF TXT_COMMAND_STR
TXT_COMMAND_STR: DC.B 'Command',$00
	XDEF TXT_CLI_STR
TXT_CLI_STR: DC.B 'CLI',$00
	XDEF TXT_WB_STR
TXT_WB_STR: DC.B 'WB',$00
	XDEF TXT_NOCLI_STR
TXT_NOCLI_STR: DC.B 'No CLI',$00
	XDEF TXT_AREXX_STR
TXT_AREXX_STR: DC.B 'ARexx',$00
	XDEF TXT_INTERNAL_STR
TXT_INTERNAL_STR: DC.B 'Internal',$00
	XDEF TXT_SPACE_STR
TXT_SPACE_STR: DC.B 'Space',$00
	XDEF TXT_BUTTMODE_STR
TXT_BUTTMODE_STR: DC.B 'Choose the starting mode',$00
	XDEF TXT_MODE_STR
TXT_MODE_STR: DC.B 'Mode',$00
	XDEF TXT_INTCOMMANDS_STR
TXT_INTCOMMANDS_STR: DC.B 'Internal commands',$00
	XDEF TXT_VARIABLES_STR
TXT_VARIABLES_STR: DC.B 'Variables',$00
	XDEF TXT_HELPE_STR
TXT_HELPE_STR: DC.B 'Help:',$00
	XDEF TXT_BUTTSTACK_STR
TXT_BUTTSTACK_STR: DC.B 'Enter the required stack',$00
	XDEF TXT_STACK_STR
TXT_STACK_STR: DC.B 'Stack',$00
	XDEF TXT_BUTTDELAY_STR
TXT_BUTTDELAY_STR: DC.B 'Choose the wanted delay',$00
	XDEF TXT_DELAY_STR
TXT_DELAY_STR: DC.B 'Delay',$00
	XDEF MSG_READSOURCE_STR
MSG_READSOURCE_STR: DC.B 'Read source',$00
	XDEF TXT_CHOOSEICON_STR
TXT_CHOOSEICON_STR: DC.B 'Choose icon',$00
	XDEF TXT_PRESSKEY_STR
TXT_PRESSKEY_STR: DC.B 'Press key',$00
	XDEF TXT_BUTTCOMMAND_STR
TXT_BUTTCOMMAND_STR: DC.B 'Command line',$00
	XDEF TXT_BUTTLOAD_STR
TXT_BUTTLOAD_STR: DC.B 'Insert a filename',$00
	XDEF TXT_BUTTLCOM_STR
TXT_BUTTLCOM_STR: DC.B 'List of Commands',$00
	XDEF TXT_BUTTCUP_STR
TXT_BUTTCUP_STR: DC.B 'Move command up',$00
	XDEF TXT_BUTTCDOWN_STR
TXT_BUTTCDOWN_STR: DC.B 'Move command down',$00
	XDEF TXT_BUTTCADD_STR
TXT_BUTTCADD_STR: DC.B 'Add command',$00
	XDEF TXT_BUTTCREM_STR
TXT_BUTTCREM_STR: DC.B 'Remove command',$00
	XDEF TXT_BUTTCNAME_STR
TXT_BUTTCNAME_STR: DC.B 'Name of command',$00
	XDEF TXT_BUTTCHELP_STR
TXT_BUTTCHELP_STR: DC.B 'Help text for the command',$00
	XDEF TXT_BUTTINT_STR
TXT_BUTTINT_STR: DC.B 'Choose internal command',$00
	XDEF TXT_BUTTOPTIONS_STR
TXT_BUTTOPTIONS_STR: DC.B 'List of options',$00
	XDEF TXT_ICONS_STR
TXT_ICONS_STR: DC.B 'Icons',$00
	XDEF TXT_BUTTONS_STR
TXT_BUTTONS_STR: DC.B 'Buttons',$00
	XDEF TXT_LISTERS_STR
TXT_LISTERS_STR: DC.B 'Listers',$00
	XDEF TXT_BUTTGTICON_STR
TXT_BUTTGTICON_STR: DC.B 'The icon for the command',$00
	XDEF TXT_BUTTPREVIEW_STR
TXT_BUTTPREVIEW_STR: DC.B 'Preview of icon(s)',$00
	XDEF TXT_BUTTKEY_STR
TXT_BUTTKEY_STR: DC.B 'Get the raw code of a key',$00
	XDEF TXT_BUTTSTRKEY_STR
TXT_BUTTSTRKEY_STR: DC.B 'Activation key for the command',$00
	XDEF TXT_BUTTCHKEY_STR
TXT_BUTTCHKEY_STR: DC.B 'The type of the key',$00
	XDEF TXT_SHOWHELP_STR
TXT_SHOWHELP_STR: DC.B 'Show Help',$00
	XDEF TXT_WINDOW_STR
TXT_WINDOW_STR: DC.B 'Window',$00
	XDEF TXT_ACTIONS_STR
TXT_ACTIONS_STR: DC.B 'Actions',$00
	XDEF TXT_DISPINFO_STR
TXT_DISPINFO_STR: DC.B 'Display icons',$00
	XDEF TXT_DISPTIME_STR
TXT_DISPTIME_STR: DC.B 'Display also time',$00
	XDEF TXT_PARENT_STR
TXT_PARENT_STR: DC.B 'Parent',$00
	XDEF TXT_PATHS_STR
TXT_PATHS_STR: DC.B 'Paths',$00
	XDEF TXT_HEIGHT_STR
TXT_HEIGHT_STR: DC.B 'Height',$00
	XDEF TXT_ICONSTART_STR
TXT_ICONSTART_STR: DC.B 'Start as icon',$00
	XDEF TXT_LEFTEDGE_STR
TXT_LEFTEDGE_STR: DC.B 'Left edge',$00
	XDEF TXT_MUIQUIT_STR
TXT_MUIQUIT_STR: DC.B 'Iconify by close gadget',$00
	XDEF TXT_TOPEDGE_STR
TXT_TOPEDGE_STR: DC.B 'Top edge',$00
	XDEF TXT_WIDTH_STR
TXT_WIDTH_STR: DC.B 'Width',$00
	XDEF TXT_CONFIRMREPLACE_STR
TXT_CONFIRMREPLACE_STR: DC.B 'Confirm replace',$00
	XDEF TXT_COPYICONS_STR
TXT_COPYICONS_STR: DC.B 'Copy icons',$00
	XDEF TXT_CREATEICONS_STR
TXT_CREATEICONS_STR: DC.B 'Create icons',$00
	XDEF TXT_DATESTRING_STR
TXT_DATESTRING_STR: DC.B 'Show date as text',$00
	XDEF TXT_DRAWERSFIRST_STR
TXT_DRAWERSFIRST_STR: DC.B 'Show drawers first',$00
	XDEF TXT_GENERAL_STR
TXT_GENERAL_STR: DC.B 'General',$00
	XDEF TXT_CLISIZE_STR
TXT_CLISIZE_STR: DC.B 'Cli size',$00
	XDEF TXT_CHOOSEFILE_STR
TXT_CHOOSEFILE_STR: DC.B 'Choose file',$00
	XDEF TXT_PATH_STR
TXT_PATH_STR: DC.B 'Path',$00
	XDEF TXT_NOTAVAIL_STR
TXT_NOTAVAIL_STR: DC.B 'This function is not yet available.',$00
	XDEF TXT_OPENPREFS_STR
TXT_OPENPREFS_STR: DC.B 'Open ClassAction preference file',$00
	XDEF TXT_SAVEPREFS_STR
TXT_SAVEPREFS_STR: DC.B 'Save ClassAction preference file',$00
	XDEF TXT_SMALLIM_STR
TXT_SMALLIM_STR: DC.B 'Use small images',$00
	XDEF TXT_EDIT_STR
TXT_EDIT_STR: DC.B 'Edit',$00
	XDEF MEN_LASTSAVED_STR
MEN_LASTSAVED_STR: DC.B 'L_Last saved',$00
	XDEF MEN_OPEN_STR
MEN_OPEN_STR: DC.B 'O_Open...',$00
	XDEF MEN_RESET_STR
MEN_RESET_STR: DC.B 'D_Reset to defaults',$00
	XDEF MEN_RESTORE_STR
MEN_RESTORE_STR: DC.B 'R_Restore',$00
	XDEF TXT_BOTTOMICONS_STR
TXT_BOTTOMICONS_STR: DC.B 'Bottom icons',$00
	XDEF TXT_CHECKFIT_STR
TXT_CHECKFIT_STR: DC.B 'Check space before copying',$00
	XDEF ERR_SAVEPREFS_STR
ERR_SAVEPREFS_STR: DC.B 'Couldn',39,'t save prefs!',$00
	XDEF TXT_HIGHDIRS_STR
TXT_HIGHDIRS_STR: DC.B 'Highlight directories',$00
	XDEF TXT_KEYCOM_STR
TXT_KEYCOM_STR: DC.B 'Tool menu',$00
	XDEF TXT_REPLACETOOLTYPES_STR
TXT_REPLACETOOLTYPES_STR: DC.B 'Now your old tooltypes will be loaded and saved in the new format.',$00
	XDEF TXT_SHOWIM_STR
TXT_SHOWIM_STR: DC.B 'Show images',$00
	XDEF TXT_TOPICONS_STR
TXT_TOPICONS_STR: DC.B 'Top icons',$00
	XDEF MEN_SAVEAS_STR
MEN_SAVEAS_STR: DC.B 'S_Save as ...',$00
	XDEF TXT_WHEREISCA_STR
TXT_WHEREISCA_STR: DC.B 'Where is your old ClassAction program file?',$00
	XDEF TXT_APPX_STR
TXT_APPX_STR: DC.B 'AppIcon left edge',$00
	XDEF TXT_APPY_STR
TXT_APPY_STR: DC.B 'AppIcon top edge',$00
	XDEF TXT_DSTSTARTPATH_STR
TXT_DSTSTARTPATH_STR: DC.B 'Destination start path',$00
	XDEF TXT_PUBLICSCREEN_STR
TXT_PUBLICSCREEN_STR: DC.B 'Public screen',$00
	XDEF TXT_SRCSTARTPATH_STR
TXT_SRCSTARTPATH_STR: DC.B 'Source start path',$00
	XDEF TXT_SHOWDEVS_STR
TXT_SHOWDEVS_STR: DC.B 'Show devices',$00
	XDEF TXT_DELETEICONS_STR
TXT_DELETEICONS_STR: DC.B 'Delete icons',$00
	XDEF TXT_MAXPATHS_STR
TXT_MAXPATHS_STR: DC.B 'Cached paths',$00
	XDEF TXT_MAXTABS_STR
TXT_MAXTABS_STR: DC.B 'Path buttons',$00
	XDEF TXT_PATHNOTIFY_STR
TXT_PATHNOTIFY_STR: DC.B 'Update on change',$00
	XDEF TXT_REFRESH_STR
TXT_REFRESH_STR: DC.B 'Refresh',$00
	XDEF TXT_LISTERFONT_STR
TXT_LISTERFONT_STR: DC.B 'Lister font',$00
	XDEF TXT_MENUFONT_STR
TXT_MENUFONT_STR: DC.B 'Menu font',$00
	XDEF TXT_BACKGROUND_STR
TXT_BACKGROUND_STR: DC.B 'Background',$00
	XDEF MSG_DELETEPROTECTED_STR
MSG_DELETEPROTECTED_STR: DC.B 'Delete protected files',$00
	XDEF TXT_PATHMENU_STR
TXT_PATHMENU_STR: DC.B 'Path menu',$00
	XDEF MSG_VERTICAL_STR
MSG_VERTICAL_STR: DC.B 'Vertically arranged',$00
	XDEF MEN_HELP_STR
MEN_HELP_STR: DC.B 'H_Help',$00
	XDEF MSG_SUPPORTEDARCHIVES_STR
MSG_SUPPORTEDARCHIVES_STR: DC.B 'Supported archives',$00
	XDEF MSG_BUTTOPENICONS_STR
MSG_BUTTOPENICONS_STR: DC.B 'Open Images',$00
	XDEF MSG_ASYNC_STR
MSG_ASYNC_STR: DC.B 'Async',$00
	XDEF MSG_READDEST_STR
MSG_READDEST_STR: DC.B 'Read dest',$00
	XDEF MSG_BUFFERSIZE_STR
MSG_BUFFERSIZE_STR: DC.B 'Buffer size in KB',$00
	XDEF MSG_COPYANDDELETE_STR
MSG_COPYANDDELETE_STR: DC.B 'Copy and delete',$00
	XDEF MSG_COUNTFILES_STR
MSG_COUNTFILES_STR: DC.B 'Count files before copy',$00
	XDEF MSG_HIDEKEY_STR
MSG_HIDEKEY_STR: DC.B 'Hide key',$00
	XDEF MEN_SHOWHELP_STR
MEN_SHOWHELP_STR: DC.B '?_Show help',$00
	XDEF MSG_POPUPKEY_STR
MSG_POPUPKEY_STR: DC.B 'Popup key',$00
	XDEF MSG_PULLDOWNMENU_STR
MSG_PULLDOWNMENU_STR: DC.B 'Menu is pulldown menu',$00
	XDEF MSG_REPLACEVERSION_STR
MSG_REPLACEVERSION_STR: DC.B 'Replace older versions when copying',$00
	XDEF MSG_SHOWVERSION_STR
MSG_SHOWVERSION_STR: DC.B 'Show version when replacing',$00
	XDEF MSG_NAME_STR
MSG_NAME_STR: DC.B 'Name',$00
	XDEF MSG_PATH_STR
MSG_PATH_STR: DC.B 'Path',$00
	XDEF TXT_BUTTLPATHS_STR
TXT_BUTTLPATHS_STR: DC.B 'List of Paths',$00
	XDEF MSG_OPENWITH_STR
MSG_OPENWITH_STR: DC.B 'Open with',$00
	XDEF MSG_PATHLIST_STR
MSG_PATHLIST_STR: DC.B 'Path list',$00
	XDEF TXT_BUTTPUP_STR
TXT_BUTTPUP_STR: DC.B 'Move path up',$00
	XDEF TXT_BUTTPDOWN_STR
TXT_BUTTPDOWN_STR: DC.B 'Move path down',$00
	XDEF TXT_BUTTPADD_STR
TXT_BUTTPADD_STR: DC.B 'Add path',$00
	XDEF TXT_BUTTPREM_STR
TXT_BUTTPREM_STR: DC.B 'Remove path',$00
	XDEF MSG_ENTERPATH_STR
MSG_ENTERPATH_STR: DC.B 'Please specify the path',$00
	XDEF MSG_ENTERPATHTITLE_STR
MSG_ENTERPATHTITLE_STR: DC.B 'Please enter the title for the path:',$00
	XDEF MSG_TABBUTTONSTRANSPARENT_STR
MSG_TABBUTTONSTRANSPARENT_STR: DC.B 'Path buttons transparent',$00
	XDEF MSG_VOLUME_STR
MSG_VOLUME_STR: DC.B 'Volume',$00
	XDEF ERR_DELCLASS_STR
ERR_DELCLASS_STR: DC.B 'This class cannot be deleted.',$00
	XDEF MSG_BUTTCLASSIMAGE_STR
MSG_BUTTCLASSIMAGE_STR: DC.B 'Image for this class',$00
	XDEF MSG_IMAGE_STR
MSG_IMAGE_STR: DC.B 'Image',$00
	XDEF MSG_BUTTLOADIMAGE_STR
MSG_BUTTLOADIMAGE_STR: DC.B 'Choose an image file',$00
	XDEF MSG_CLASSIMAGES_STR
MSG_CLASSIMAGES_STR: DC.B 'Use class images',$00
	XDEF MSG_OWNSCREEN_STR
MSG_OWNSCREEN_STR: DC.B 'Own screen',$00
	XDEF MSG_ARCHIVE_STR
MSG_ARCHIVE_STR: DC.B 'Archive',$00
	XDEF MSG_ONLYPATTERNS_STR
MSG_ONLYPATTERNS_STR: DC.B 'Check only patterns',$00
	XDEF MSG_DUPLICATE_STR
MSG_DUPLICATE_STR: DC.B 'Duplicate',$00
	XDEF MSG_PASTE_STR
MSG_PASTE_STR: DC.B 'Paste',$00
	XDEF MSG_LEARN_STR
MSG_LEARN_STR: DC.B 'Learn',$00
	XDEF MSG_IMPORT_STR
MSG_IMPORT_STR: DC.B 'Import',$00
	XDEF MSG_EXPORT_STR
MSG_EXPORT_STR: DC.B 'Export',$00
	XDEF MSG_COPY_STR
MSG_COPY_STR: DC.B 'Copy',$00
	XDEF MSG_BLUE_STR
MSG_BLUE_STR: DC.B 'Blue',$00
	XDEF MSG_DATEFORMAT_STR
MSG_DATEFORMAT_STR: DC.B 'Date format',$00
	XDEF MSG_EXPORTCLASS_STR
MSG_EXPORTCLASS_STR: DC.B 'Export class',$00
	XDEF MSG_GREEN_STR
MSG_GREEN_STR: DC.B 'Green',$00
	XDEF MSG_IMPORTCLASS_STR
MSG_IMPORTCLASS_STR: DC.B 'Import class',$00
	XDEF MSG_RED_STR
MSG_RED_STR: DC.B 'Red',$00
	XDEF MSG_USEEXALL_STR
MSG_USEEXALL_STR: DC.B 'Use ExAll()',$00
	XDEF MSG_USEREACTIONREQUEST_STR
MSG_USEREACTIONREQUEST_STR: DC.B 'Reaction requesters',$00
	XDEF MSG_BUTTDIR_STR
MSG_BUTTDIR_STR: DC.B 'Work directory',$00
	XDEF MSG_SOURCE_STR
MSG_SOURCE_STR: DC.B 'source',$00
	XDEF MSG_DESTINATION_STR
MSG_DESTINATION_STR: DC.B 'destination',$00
	XDEF MSG_PROGDIR_STR
MSG_PROGDIR_STR: DC.B 'program dir',$00
	XDEF MSG_CD_STR
MSG_CD_STR: DC.B 'CD',$00
	XDEF MSG_CONFIRMDELETE_STR
MSG_CONFIRMDELETE_STR: DC.B 'Confirm delete',$00
	XDEF MSG_EXALLFILES_STR
MSG_EXALLFILES_STR: DC.B 'Files per ExAll() call',$00

	ENDC ; CATCOMP_STRINGS


;-----------------------------------------------------------------------------


	IFD CATCOMP_ARRAY

   STRUCTURE CatCompArrayType,0
	LONG cca_ID
	APTR cca_Str
   LABEL CatCompArrayType_SIZEOF

	CNOP 0,4

	XDEF CatCompArray
CatCompArray:
	XDEF _CatCompArray
_CatCompArray:
AS0:	DC.L TXT_CLASSNAME,TXT_CLASSNAME_STR
AS1:	DC.L TXT_MATCHNAME,TXT_MATCHNAME_STR
AS2:	DC.L TXT_OFFSET1,TXT_OFFSET1_STR
AS3:	DC.L TXT_OFFSET2,TXT_OFFSET2_STR
AS4:	DC.L TXT_OFFSET3,TXT_OFFSET3_STR
AS5:	DC.L TXT_OFFSET4,TXT_OFFSET4_STR
AS6:	DC.L TXT_OFFSET5,TXT_OFFSET5_STR
AS7:	DC.L TXT_BUTTLST1,TXT_BUTTLST1_STR
AS8:	DC.L TXT_BUTTCLASS,TXT_BUTTCLASS_STR
AS9:	DC.L TXT_BUTTMATCH,TXT_BUTTMATCH_STR
AS10:	DC.L TXT_BUTTCHOFF,TXT_BUTTCHOFF_STR
AS11:	DC.L TXT_BUTTOFFSET,TXT_BUTTOFFSET_STR
AS12:	DC.L TXT_BUTTADD,TXT_BUTTADD_STR
AS13:	DC.L TXT_BUTTREMOVE,TXT_BUTTREMOVE_STR
AS14:	DC.L TXT_BUTTLST2,TXT_BUTTLST2_STR
AS15:	DC.L TXT_BUTTANAME,TXT_BUTTANAME_STR
AS16:	DC.L TXT_BUTTUP,TXT_BUTTUP_STR
AS17:	DC.L TXT_BUTTDOWN,TXT_BUTTDOWN_STR
AS18:	DC.L TXT_BUTTADD2,TXT_BUTTADD2_STR
AS19:	DC.L TXT_BUTTREMOVE2,TXT_BUTTREMOVE2_STR
AS20:	DC.L TXT_ABOUT,TXT_ABOUT_STR
AS21:	DC.L TXT_PROJECT,TXT_PROJECT_STR
AS22:	DC.L MEN_QUIT,MEN_QUIT_STR
AS23:	DC.L ERR_GENERAL,ERR_GENERAL_STR
AS24:	DC.L ERR_NOCONFIG,ERR_NOCONFIG_STR
AS25:	DC.L ERR_NOICON,ERR_NOICON_STR
AS26:	DC.L ERR_NOLIB,ERR_NOLIB_STR
AS27:	DC.L TXT_DELACTION,TXT_DELACTION_STR
AS28:	DC.L TXT_DELCLASS,TXT_DELCLASS_STR
AS29:	DC.L TXT_NEWACTION,TXT_NEWACTION_STR
AS30:	DC.L TXT_NEWCLASS,TXT_NEWCLASS_STR
AS31:	DC.L TXT_NOACT,TXT_NOACT_STR
AS32:	DC.L TXT_INFORMATION,TXT_INFORMATION_STR
AS33:	DC.L TXT_OK,TXT_OK_STR
AS34:	DC.L TXT_YESNO,TXT_YESNO_STR
AS35:	DC.L ERR_CONFIGNOTVALID,ERR_CONFIGNOTVALID_STR
AS36:	DC.L ERR_GENERICNOTVALID,ERR_GENERICNOTVALID_STR
AS37:	DC.L TXT_GENERIC,TXT_GENERIC_STR
AS38:	DC.L TXT_UNKNOWN,TXT_UNKNOWN_STR
AS39:	DC.L TXT_DIRECTORY,TXT_DIRECTORY_STR
AS40:	DC.L ERR_DIRNOTVALID,ERR_DIRNOTVALID_STR
AS41:	DC.L ERR_CONFIGCORRUPT,ERR_CONFIGCORRUPT_STR
AS42:	DC.L TXT_LCHOOSE,TXT_LCHOOSE_STR
AS43:	DC.L TXT_LCOMP,TXT_LCOMP_STR
AS44:	DC.L TXT_LPREP,TXT_LPREP_STR
AS45:	DC.L TXT_LPROG,TXT_LPROG_STR
AS46:	DC.L TXT_LEARN,TXT_LEARN_STR
AS47:	DC.L TXT_ACCEPT,TXT_ACCEPT_STR
AS48:	DC.L TXT_BUTTLACCEPT,TXT_BUTTLACCEPT_STR
AS49:	DC.L TXT_BUTTLCANCEL,TXT_BUTTLCANCEL_STR
AS50:	DC.L TXT_PROG,TXT_PROG_STR
AS51:	DC.L TXT_LMEMORY,TXT_LMEMORY_STR
AS52:	DC.L TXT_LNEED,TXT_LNEED_STR
AS53:	DC.L TXT_LNOTHING,TXT_LNOTHING_STR
AS54:	DC.L TXT_COPYRIGHT,TXT_COPYRIGHT_STR
AS55:	DC.L TXT_OPTIONS,TXT_OPTIONS_STR
AS56:	DC.L TXT_COMMANDS,TXT_COMMANDS_STR
AS57:	DC.L TXT_CLASSES,TXT_CLASSES_STR
AS58:	DC.L TXT_SAVE,TXT_SAVE_STR
AS59:	DC.L TXT_BUTTSAVE,TXT_BUTTSAVE_STR
AS60:	DC.L TXT_USE,TXT_USE_STR
AS61:	DC.L TXT_BUTTUSE,TXT_BUTTUSE_STR
AS62:	DC.L TXT_CANCEL,TXT_CANCEL_STR
AS63:	DC.L TXT_BUTTCANCEL,TXT_BUTTCANCEL_STR
AS64:	DC.L TXT_ISSURE,TXT_ISSURE_STR
AS65:	DC.L TXT_ACTIKEY,TXT_ACTIKEY_STR
AS66:	DC.L TXT_SELRAWKEY,TXT_SELRAWKEY_STR
AS67:	DC.L TXT_NAMEE,TXT_NAMEE_STR
AS68:	DC.L TXT_ICON,TXT_ICON_STR
AS69:	DC.L TXT_ADD,TXT_ADD_STR
AS70:	DC.L TXT_REMOVE,TXT_REMOVE_STR
AS71:	DC.L TXT_NAME,TXT_NAME_STR
AS72:	DC.L TXT_BUTTCOMM,TXT_BUTTCOMM_STR
AS73:	DC.L TXT_REQPF2,TXT_REQPF2_STR
AS74:	DC.L TXT_REQS2,TXT_REQS2_STR
AS75:	DC.L TXT_REQB2,TXT_REQB2_STR
AS76:	DC.L TXT_REQX2,TXT_REQX2_STR
AS77:	DC.L TXT_SRC,TXT_SRC_STR
AS78:	DC.L TXT_SRCS,TXT_SRCS_STR
AS79:	DC.L TXT_DST,TXT_DST_STR
AS80:	DC.L TXT_DSTS,TXT_DSTS_STR
AS81:	DC.L TXT_REQF,TXT_REQF_STR
AS82:	DC.L TXT_REQD,TXT_REQD_STR
AS83:	DC.L TXT_REQT,TXT_REQT_STR
AS84:	DC.L TXT_SURE,TXT_SURE_STR
AS85:	DC.L TXT_COMMAND,TXT_COMMAND_STR
AS86:	DC.L TXT_CLI,TXT_CLI_STR
AS87:	DC.L TXT_WB,TXT_WB_STR
AS88:	DC.L TXT_NOCLI,TXT_NOCLI_STR
AS89:	DC.L TXT_AREXX,TXT_AREXX_STR
AS90:	DC.L TXT_INTERNAL,TXT_INTERNAL_STR
AS91:	DC.L TXT_SPACE,TXT_SPACE_STR
AS92:	DC.L TXT_BUTTMODE,TXT_BUTTMODE_STR
AS93:	DC.L TXT_MODE,TXT_MODE_STR
AS94:	DC.L TXT_INTCOMMANDS,TXT_INTCOMMANDS_STR
AS95:	DC.L TXT_VARIABLES,TXT_VARIABLES_STR
AS96:	DC.L TXT_HELPE,TXT_HELPE_STR
AS97:	DC.L TXT_BUTTSTACK,TXT_BUTTSTACK_STR
AS98:	DC.L TXT_STACK,TXT_STACK_STR
AS99:	DC.L TXT_BUTTDELAY,TXT_BUTTDELAY_STR
AS100:	DC.L TXT_DELAY,TXT_DELAY_STR
AS101:	DC.L MSG_READSOURCE,MSG_READSOURCE_STR
AS102:	DC.L TXT_CHOOSEICON,TXT_CHOOSEICON_STR
AS103:	DC.L TXT_PRESSKEY,TXT_PRESSKEY_STR
AS104:	DC.L TXT_BUTTCOMMAND,TXT_BUTTCOMMAND_STR
AS105:	DC.L TXT_BUTTLOAD,TXT_BUTTLOAD_STR
AS106:	DC.L TXT_BUTTLCOM,TXT_BUTTLCOM_STR
AS107:	DC.L TXT_BUTTCUP,TXT_BUTTCUP_STR
AS108:	DC.L TXT_BUTTCDOWN,TXT_BUTTCDOWN_STR
AS109:	DC.L TXT_BUTTCADD,TXT_BUTTCADD_STR
AS110:	DC.L TXT_BUTTCREM,TXT_BUTTCREM_STR
AS111:	DC.L TXT_BUTTCNAME,TXT_BUTTCNAME_STR
AS112:	DC.L TXT_BUTTCHELP,TXT_BUTTCHELP_STR
AS113:	DC.L TXT_BUTTINT,TXT_BUTTINT_STR
AS114:	DC.L TXT_BUTTOPTIONS,TXT_BUTTOPTIONS_STR
AS115:	DC.L TXT_ICONS,TXT_ICONS_STR
AS116:	DC.L TXT_BUTTONS,TXT_BUTTONS_STR
AS117:	DC.L TXT_LISTERS,TXT_LISTERS_STR
AS118:	DC.L TXT_BUTTGTICON,TXT_BUTTGTICON_STR
AS119:	DC.L TXT_BUTTPREVIEW,TXT_BUTTPREVIEW_STR
AS120:	DC.L TXT_BUTTKEY,TXT_BUTTKEY_STR
AS121:	DC.L TXT_BUTTSTRKEY,TXT_BUTTSTRKEY_STR
AS122:	DC.L TXT_BUTTCHKEY,TXT_BUTTCHKEY_STR
AS123:	DC.L TXT_SHOWHELP,TXT_SHOWHELP_STR
AS124:	DC.L TXT_WINDOW,TXT_WINDOW_STR
AS125:	DC.L TXT_ACTIONS,TXT_ACTIONS_STR
AS126:	DC.L TXT_DISPINFO,TXT_DISPINFO_STR
AS127:	DC.L TXT_DISPTIME,TXT_DISPTIME_STR
AS128:	DC.L TXT_PARENT,TXT_PARENT_STR
AS129:	DC.L TXT_PATHS,TXT_PATHS_STR
AS130:	DC.L TXT_HEIGHT,TXT_HEIGHT_STR
AS131:	DC.L TXT_ICONSTART,TXT_ICONSTART_STR
AS132:	DC.L TXT_LEFTEDGE,TXT_LEFTEDGE_STR
AS133:	DC.L TXT_MUIQUIT,TXT_MUIQUIT_STR
AS134:	DC.L TXT_TOPEDGE,TXT_TOPEDGE_STR
AS135:	DC.L TXT_WIDTH,TXT_WIDTH_STR
AS136:	DC.L TXT_CONFIRMREPLACE,TXT_CONFIRMREPLACE_STR
AS137:	DC.L TXT_COPYICONS,TXT_COPYICONS_STR
AS138:	DC.L TXT_CREATEICONS,TXT_CREATEICONS_STR
AS139:	DC.L TXT_DATESTRING,TXT_DATESTRING_STR
AS140:	DC.L TXT_DRAWERSFIRST,TXT_DRAWERSFIRST_STR
AS141:	DC.L TXT_GENERAL,TXT_GENERAL_STR
AS142:	DC.L TXT_CLISIZE,TXT_CLISIZE_STR
AS143:	DC.L TXT_CHOOSEFILE,TXT_CHOOSEFILE_STR
AS144:	DC.L TXT_PATH,TXT_PATH_STR
AS145:	DC.L TXT_NOTAVAIL,TXT_NOTAVAIL_STR
AS146:	DC.L TXT_OPENPREFS,TXT_OPENPREFS_STR
AS147:	DC.L TXT_SAVEPREFS,TXT_SAVEPREFS_STR
AS148:	DC.L TXT_SMALLIM,TXT_SMALLIM_STR
AS149:	DC.L TXT_EDIT,TXT_EDIT_STR
AS150:	DC.L MEN_LASTSAVED,MEN_LASTSAVED_STR
AS151:	DC.L MEN_OPEN,MEN_OPEN_STR
AS152:	DC.L MEN_RESET,MEN_RESET_STR
AS153:	DC.L MEN_RESTORE,MEN_RESTORE_STR
AS154:	DC.L TXT_BOTTOMICONS,TXT_BOTTOMICONS_STR
AS155:	DC.L TXT_CHECKFIT,TXT_CHECKFIT_STR
AS156:	DC.L ERR_SAVEPREFS,ERR_SAVEPREFS_STR
AS157:	DC.L TXT_HIGHDIRS,TXT_HIGHDIRS_STR
AS158:	DC.L TXT_KEYCOM,TXT_KEYCOM_STR
AS159:	DC.L TXT_REPLACETOOLTYPES,TXT_REPLACETOOLTYPES_STR
AS160:	DC.L TXT_SHOWIM,TXT_SHOWIM_STR
AS161:	DC.L TXT_TOPICONS,TXT_TOPICONS_STR
AS162:	DC.L MEN_SAVEAS,MEN_SAVEAS_STR
AS163:	DC.L TXT_WHEREISCA,TXT_WHEREISCA_STR
AS164:	DC.L TXT_APPX,TXT_APPX_STR
AS165:	DC.L TXT_APPY,TXT_APPY_STR
AS166:	DC.L TXT_DSTSTARTPATH,TXT_DSTSTARTPATH_STR
AS167:	DC.L TXT_PUBLICSCREEN,TXT_PUBLICSCREEN_STR
AS168:	DC.L TXT_SRCSTARTPATH,TXT_SRCSTARTPATH_STR
AS169:	DC.L TXT_SHOWDEVS,TXT_SHOWDEVS_STR
AS170:	DC.L TXT_DELETEICONS,TXT_DELETEICONS_STR
AS171:	DC.L TXT_MAXPATHS,TXT_MAXPATHS_STR
AS172:	DC.L TXT_MAXTABS,TXT_MAXTABS_STR
AS173:	DC.L TXT_PATHNOTIFY,TXT_PATHNOTIFY_STR
AS174:	DC.L TXT_REFRESH,TXT_REFRESH_STR
AS175:	DC.L TXT_LISTERFONT,TXT_LISTERFONT_STR
AS176:	DC.L TXT_MENUFONT,TXT_MENUFONT_STR
AS177:	DC.L TXT_BACKGROUND,TXT_BACKGROUND_STR
AS178:	DC.L MSG_DELETEPROTECTED,MSG_DELETEPROTECTED_STR
AS179:	DC.L TXT_PATHMENU,TXT_PATHMENU_STR
AS180:	DC.L MSG_VERTICAL,MSG_VERTICAL_STR
AS181:	DC.L MEN_HELP,MEN_HELP_STR
AS182:	DC.L MSG_SUPPORTEDARCHIVES,MSG_SUPPORTEDARCHIVES_STR
AS183:	DC.L MSG_BUTTOPENICONS,MSG_BUTTOPENICONS_STR
AS184:	DC.L MSG_ASYNC,MSG_ASYNC_STR
AS185:	DC.L MSG_READDEST,MSG_READDEST_STR
AS186:	DC.L MSG_BUFFERSIZE,MSG_BUFFERSIZE_STR
AS187:	DC.L MSG_COPYANDDELETE,MSG_COPYANDDELETE_STR
AS188:	DC.L MSG_COUNTFILES,MSG_COUNTFILES_STR
AS189:	DC.L MSG_HIDEKEY,MSG_HIDEKEY_STR
AS190:	DC.L MEN_SHOWHELP,MEN_SHOWHELP_STR
AS191:	DC.L MSG_POPUPKEY,MSG_POPUPKEY_STR
AS192:	DC.L MSG_PULLDOWNMENU,MSG_PULLDOWNMENU_STR
AS193:	DC.L MSG_REPLACEVERSION,MSG_REPLACEVERSION_STR
AS194:	DC.L MSG_SHOWVERSION,MSG_SHOWVERSION_STR
AS195:	DC.L MSG_NAME,MSG_NAME_STR
AS196:	DC.L MSG_PATH,MSG_PATH_STR
AS197:	DC.L TXT_BUTTLPATHS,TXT_BUTTLPATHS_STR
AS198:	DC.L MSG_OPENWITH,MSG_OPENWITH_STR
AS199:	DC.L MSG_PATHLIST,MSG_PATHLIST_STR
AS200:	DC.L TXT_BUTTPUP,TXT_BUTTPUP_STR
AS201:	DC.L TXT_BUTTPDOWN,TXT_BUTTPDOWN_STR
AS202:	DC.L TXT_BUTTPADD,TXT_BUTTPADD_STR
AS203:	DC.L TXT_BUTTPREM,TXT_BUTTPREM_STR
AS204:	DC.L MSG_ENTERPATH,MSG_ENTERPATH_STR
AS205:	DC.L MSG_ENTERPATHTITLE,MSG_ENTERPATHTITLE_STR
AS206:	DC.L MSG_TABBUTTONSTRANSPARENT,MSG_TABBUTTONSTRANSPARENT_STR
AS207:	DC.L MSG_VOLUME,MSG_VOLUME_STR
AS208:	DC.L ERR_DELCLASS,ERR_DELCLASS_STR
AS209:	DC.L MSG_BUTTCLASSIMAGE,MSG_BUTTCLASSIMAGE_STR
AS210:	DC.L MSG_IMAGE,MSG_IMAGE_STR
AS211:	DC.L MSG_BUTTLOADIMAGE,MSG_BUTTLOADIMAGE_STR
AS212:	DC.L MSG_CLASSIMAGES,MSG_CLASSIMAGES_STR
AS213:	DC.L MSG_OWNSCREEN,MSG_OWNSCREEN_STR
AS214:	DC.L MSG_ARCHIVE,MSG_ARCHIVE_STR
AS215:	DC.L MSG_ONLYPATTERNS,MSG_ONLYPATTERNS_STR
AS216:	DC.L MSG_DUPLICATE,MSG_DUPLICATE_STR
AS217:	DC.L MSG_PASTE,MSG_PASTE_STR
AS218:	DC.L MSG_LEARN,MSG_LEARN_STR
AS219:	DC.L MSG_IMPORT,MSG_IMPORT_STR
AS220:	DC.L MSG_EXPORT,MSG_EXPORT_STR
AS221:	DC.L MSG_COPY,MSG_COPY_STR
AS222:	DC.L MSG_BLUE,MSG_BLUE_STR
AS223:	DC.L MSG_DATEFORMAT,MSG_DATEFORMAT_STR
AS224:	DC.L MSG_EXPORTCLASS,MSG_EXPORTCLASS_STR
AS225:	DC.L MSG_GREEN,MSG_GREEN_STR
AS226:	DC.L MSG_IMPORTCLASS,MSG_IMPORTCLASS_STR
AS227:	DC.L MSG_RED,MSG_RED_STR
AS228:	DC.L MSG_USEEXALL,MSG_USEEXALL_STR
AS229:	DC.L MSG_USEREACTIONREQUEST,MSG_USEREACTIONREQUEST_STR
AS230:	DC.L MSG_BUTTDIR,MSG_BUTTDIR_STR
AS231:	DC.L MSG_SOURCE,MSG_SOURCE_STR
AS232:	DC.L MSG_DESTINATION,MSG_DESTINATION_STR
AS233:	DC.L MSG_PROGDIR,MSG_PROGDIR_STR
AS234:	DC.L MSG_CD,MSG_CD_STR
AS235:	DC.L MSG_CONFIRMDELETE,MSG_CONFIRMDELETE_STR
AS236:	DC.L MSG_EXALLFILES,MSG_EXALLFILES_STR

	ENDC ; CATCOMP_ARRAY


;-----------------------------------------------------------------------------


	IFD CATCOMP_BLOCK

	XDEF CatCompBlock
CatCompBlock:
	XDEF _CatCompBlock
_CatCompBlock:
	DC.L $103
	DC.W $C
	DC.B 'Class name',$00,$00
	DC.L $104
	DC.W $8
	DC.B 'Pattern',$00
	DC.L $105
	DC.W $A
	DC.B 'Offset #1',$00
	DC.L $106
	DC.W $A
	DC.B 'Offset #2',$00
	DC.L $107
	DC.W $A
	DC.B 'Offset #3',$00
	DC.L $108
	DC.W $A
	DC.B 'Offset #4',$00
	DC.L $109
	DC.W $A
	DC.B 'Offset #5',$00
	DC.L $12D
	DC.W $18
	DC.B 'List of defined classes',$00
	DC.L $12E
	DC.W $12
	DC.B 'Name of the class',$00
	DC.L $12F
	DC.W $1E
	DC.B 'Pattern that must be matched',$00,$00
	DC.L $130
	DC.W $18
	DC.B 'Select one of 6 Offsets',$00
	DC.L $131
	DC.W $18
	DC.B 'Enter the matching text',$00
	DC.L $132
	DC.W $10
	DC.B 'Add a new class',$00
	DC.L $133
	DC.W $12
	DC.B 'Remove this class',$00
	DC.L $135
	DC.W $18
	DC.B 'List of defined actions',$00
	DC.L $136
	DC.W $18
	DC.B 'The name of the action',$00,$00
	DC.L $13A
	DC.W $14
	DC.B 'Move this action up',$00
	DC.L $13B
	DC.W $16
	DC.B 'Move this action down',$00
	DC.L $13E
	DC.W $12
	DC.B 'Add a new action',$00,$00
	DC.L $13F
	DC.W $14
	DC.B 'Remove this action',$00,$00
	DC.L $143
	DC.W $6
	DC.B 'About',$00
	DC.L $144
	DC.W $8
	DC.B 'Project',$00
	DC.L $145
	DC.W $8
	DC.B 'Q_Quit',$00,$00
	DC.L $147
	DC.W $22
	DC.B 'An unspecified error has occured.',$00
	DC.L $148
	DC.W $18
	DC.B 'Config file not found.',$00,$00
	DC.L $149
	DC.W $12
	DC.B 'There is no icon!',$00
	DC.L $14A
	DC.W $26
	DC.B 'Library not found. Perhaps wrong OS.',$00,$00
	DC.L $14B
	DC.W $16
	DC.B 'Delete this action ?',$00,$00
	DC.L $14C
	DC.W $14
	DC.B 'Delete this class ?',$00
	DC.L $14D
	DC.W $12
	DC.B '<New action #%d>',$00,$00
	DC.L $14E
	DC.W $10
	DC.B '<New class #%d>',$00
	DC.L $14F
	DC.W $A
	DC.B 'No action',$00
	DC.L $150
	DC.W $C
	DC.B 'Information',$00
	DC.L $151
	DC.W $4
	DC.B 'Ok',$00,$00
	DC.L $152
	DC.W $8
	DC.B 'Yes|No',$00,$00
	DC.L $153
	DC.W $3A
	DC.B 'Your config file',10,10,'is not a valid',10,10,'ClassAction config file',$00
	DC.L $154
	DC.W $20
	DC.B 'The generic file is not valid.',$00,$00
	DC.L $155
	DC.W $10
	DC.B 'Generic actions',$00
	DC.L $156
	DC.W $E
	DC.B 'Unknown class',$00
	DC.L $157
	DC.W $A
	DC.B 'Directory',$00
	DC.L $158
	DC.W $1C
	DC.B 'The dir file is not valid.',$00,$00
	DC.L $159
	DC.W $20
	DC.B 'Your config file',10,10,'is corrupted.',$00
	DC.L $15A
	DC.W $1C
	DC.B 'Choose files to learn from.',$00
	DC.L $15B
	DC.W $14
	DC.B 'Analysis complete.',$00,$00
	DC.L $15C
	DC.W $1E
	DC.B 'Preprocessing ... please wait',$00
	DC.L $15D
	DC.W $1A
	DC.B 'Analysis in progress ...',$00,$00
	DC.L $15E
	DC.W $6
	DC.B 'Learn',$00
	DC.L $15F
	DC.W $8
	DC.B 'Accept',$00,$00
	DC.L $160
	DC.W $22
	DC.B 'Accept these offsets and strings',$00,$00
	DC.L $161
	DC.W $1C
	DC.B 'Cancel the learning process',$00
	DC.L $162
	DC.W $12
	DC.B 'ClassActionPrefs',$00,$00
	DC.L $163
	DC.W $20
	DC.B 'Not enough memory for learning.',$00
	DC.L $164
	DC.W $26
	DC.B 'I need at leat 2 files for learning.',$00,$00
	DC.L $165
	DC.W $10
	DC.B 'Nothing found.',$00,$00
	DC.L $168
	DC.W $C6
	DC.B '   %s',10,10,'© 2002 by Martin R. Elsner & Salim Gasmi',10,10,'You can contact me at'
	DC.B ' :',10,10,'Martin R. Elsner',10,'Muesener Strasse 46',10,'57223 Kreuztal',10,'Germany',10,10,'Email'
	DC.B ': email@martin-elsner.de',10,'Web: http://www.martin-elsner.de',$00
	DC.L $16A
	DC.W $8
	DC.B 'Options',$00
	DC.L $16B
	DC.W $A
	DC.B 'Commands',$00,$00
	DC.L $16C
	DC.W $8
	DC.B 'Classes',$00
	DC.L $16D
	DC.W $6
	DC.B 'Save',$00,$00
	DC.L $16E
	DC.W $12
	DC.B 'Save the changes',$00,$00
	DC.L $16F
	DC.W $4
	DC.B 'Use',$00
	DC.L $170
	DC.W $20
	DC.B 'Use the changes without saving',$00,$00
	DC.L $171
	DC.W $8
	DC.B 'Cancel',$00,$00
	DC.L $172
	DC.W $14
	DC.B 'Quit without saving',$00
	DC.L $173
	DC.W $10
	DC.B 'Are you sure ?',$00,$00
	DC.L $18E
	DC.W $10
	DC.B 'Activation key',$00,$00
	DC.L $18F
	DC.W $10
	DC.B 'Select RAW key',$00,$00
	DC.L $194
	DC.W $6
	DC.B 'Name:',$00
	DC.L $195
	DC.W $6
	DC.B 'Icon',$00,$00
	DC.L $196
	DC.W $4
	DC.B 'Add',$00
	DC.L $197
	DC.W $8
	DC.B 'Remove',$00,$00
	DC.L $1A8
	DC.W $6
	DC.B 'Name',$00,$00
	DC.L $1AA
	DC.W $12
	DC.B 'Choose a variable',$00
	DC.L $1AB
	DC.W $12
	DC.B '[F] Path+Filename',$00
	DC.L $1AC
	DC.W $22
	DC.B '[S] Path+Filename without suffix',$00,$00
	DC.L $1AD
	DC.W $E
	DC.B '[B] Filename',$00,$00
	DC.L $1AE
	DC.W $1C
	DC.B '[X] Filename without suffix',$00
	DC.L $1AF
	DC.W $1C
	DC.B '[SRC] Path of source lister',$00
	DC.L $1B0
	DC.W $24
	DC.B '[SRCS] Path of source lister + ',39,'/',39,$00,$00
	DC.L $1B1
	DC.W $22
	DC.B '[DST] Path of destination lister',$00,$00
	DC.L $1B2
	DC.W $28
	DC.B '[DSTS] Path of destination lister + ',39,'/',39,$00
	DC.L $1B3
	DC.W $1A
	DC.B '[REQF:...] Request a file',$00
	DC.L $1B4
	DC.W $20
	DC.B '[REQD:...] Request a directory',$00,$00
	DC.L $1B5
	DC.W $1A
	DC.B '[REQT:...] Request a text',$00
	DC.L $1B6
	DC.W $1E
	DC.B '[SURE:...] Confirm a command',$00,$00
	DC.L $1BB
	DC.W $8
	DC.B 'Command',$00
	DC.L $1BC
	DC.W $4
	DC.B 'CLI',$00
	DC.L $1BD
	DC.W $4
	DC.B 'WB',$00,$00
	DC.L $1BE
	DC.W $8
	DC.B 'No CLI',$00,$00
	DC.L $1BF
	DC.W $6
	DC.B 'ARexx',$00
	DC.L $1C0
	DC.W $A
	DC.B 'Internal',$00,$00
	DC.L $1C1
	DC.W $6
	DC.B 'Space',$00
	DC.L $1C2
	DC.W $1A
	DC.B 'Choose the starting mode',$00,$00
	DC.L $1C3
	DC.W $6
	DC.B 'Mode',$00,$00
	DC.L $1C4
	DC.W $12
	DC.B 'Internal commands',$00
	DC.L $1C5
	DC.W $A
	DC.B 'Variables',$00
	DC.L $1C6
	DC.W $6
	DC.B 'Help:',$00
	DC.L $1C8
	DC.W $1A
	DC.B 'Enter the required stack',$00,$00
	DC.L $1C9
	DC.W $6
	DC.B 'Stack',$00
	DC.L $1CA
	DC.W $18
	DC.B 'Choose the wanted delay',$00
	DC.L $1CB
	DC.W $6
	DC.B 'Delay',$00
	DC.L $1CC
	DC.W $C
	DC.B 'Read source',$00
	DC.L $1DA
	DC.W $C
	DC.B 'Choose icon',$00
	DC.L $1DB
	DC.W $A
	DC.B 'Press key',$00
	DC.L $1E8
	DC.W $E
	DC.B 'Command line',$00,$00
	DC.L $1E9
	DC.W $12
	DC.B 'Insert a filename',$00
	DC.L $1ED
	DC.W $12
	DC.B 'List of Commands',$00,$00
	DC.L $1EE
	DC.W $10
	DC.B 'Move command up',$00
	DC.L $1EF
	DC.W $12
	DC.B 'Move command down',$00
	DC.L $1F0
	DC.W $C
	DC.B 'Add command',$00
	DC.L $1F1
	DC.W $10
	DC.B 'Remove command',$00,$00
	DC.L $1F2
	DC.W $10
	DC.B 'Name of command',$00
	DC.L $1F3
	DC.W $1A
	DC.B 'Help text for the command',$00
	DC.L $1F4
	DC.W $18
	DC.B 'Choose internal command',$00
	DC.L $1F6
	DC.W $10
	DC.B 'List of options',$00
	DC.L $1F7
	DC.W $6
	DC.B 'Icons',$00
	DC.L $1F9
	DC.W $8
	DC.B 'Buttons',$00
	DC.L $1FA
	DC.W $8
	DC.B 'Listers',$00
	DC.L $1FB
	DC.W $1A
	DC.B 'The icon for the command',$00,$00
	DC.L $1FC
	DC.W $14
	DC.B 'Preview of icon(s)',$00,$00
	DC.L $1FD
	DC.W $1A
	DC.B 'Get the raw code of a key',$00
	DC.L $1FE
	DC.W $20
	DC.B 'Activation key for the command',$00,$00
	DC.L $1FF
	DC.W $14
	DC.B 'The type of the key',$00
	DC.L $200
	DC.W $A
	DC.B 'Show Help',$00
	DC.L $203
	DC.W $8
	DC.B 'Window',$00,$00
	DC.L $205
	DC.W $8
	DC.B 'Actions',$00
	DC.L $20C
	DC.W $E
	DC.B 'Display icons',$00
	DC.L $20D
	DC.W $12
	DC.B 'Display also time',$00
	DC.L $211
	DC.W $8
	DC.B 'Parent',$00,$00
	DC.L $212
	DC.W $6
	DC.B 'Paths',$00
	DC.L $213
	DC.W $8
	DC.B 'Height',$00,$00
	DC.L $214
	DC.W $E
	DC.B 'Start as icon',$00
	DC.L $215
	DC.W $A
	DC.B 'Left edge',$00
	DC.L $216
	DC.W $18
	DC.B 'Iconify by close gadget',$00
	DC.L $217
	DC.W $A
	DC.B 'Top edge',$00,$00
	DC.L $218
	DC.W $6
	DC.B 'Width',$00
	DC.L $219
	DC.W $10
	DC.B 'Confirm replace',$00
	DC.L $21A
	DC.W $C
	DC.B 'Copy icons',$00,$00
	DC.L $21B
	DC.W $E
	DC.B 'Create icons',$00,$00
	DC.L $21C
	DC.W $12
	DC.B 'Show date as text',$00
	DC.L $21D
	DC.W $14
	DC.B 'Show drawers first',$00,$00
	DC.L $21E
	DC.W $8
	DC.B 'General',$00
	DC.L $21F
	DC.W $A
	DC.B 'Cli size',$00,$00
	DC.L $221
	DC.W $C
	DC.B 'Choose file',$00
	DC.L $223
	DC.W $6
	DC.B 'Path',$00,$00
	DC.L $224
	DC.W $24
	DC.B 'This function is not yet available.',$00
	DC.L $225
	DC.W $22
	DC.B 'Open ClassAction preference file',$00,$00
	DC.L $228
	DC.W $22
	DC.B 'Save ClassAction preference file',$00,$00
	DC.L $22B
	DC.W $12
	DC.B 'Use small images',$00,$00
	DC.L $22C
	DC.W $6
	DC.B 'Edit',$00,$00
	DC.L $22D
	DC.W $E
	DC.B 'L_Last saved',$00,$00
	DC.L $22E
	DC.W $A
	DC.B 'O_Open...',$00
	DC.L $22F
	DC.W $14
	DC.B 'D_Reset to defaults',$00
	DC.L $230
	DC.W $A
	DC.B 'R_Restore',$00
	DC.L $232
	DC.W $E
	DC.B 'Bottom icons',$00,$00
	DC.L $234
	DC.W $1C
	DC.B 'Check space before copying',$00,$00
	DC.L $235
	DC.W $16
	DC.B 'Couldn',39,'t save prefs!',$00,$00
	DC.L $236
	DC.W $16
	DC.B 'Highlight directories',$00
	DC.L $238
	DC.W $A
	DC.B 'Tool menu',$00
	DC.L $239
	DC.W $44
	DC.B 'Now your old tooltypes will be loaded and saved in the new format.',$00,$00
	DC.L $23A
	DC.W $C
	DC.B 'Show images',$00
	DC.L $23B
	DC.W $A
	DC.B 'Top icons',$00
	DC.L $23D
	DC.W $E
	DC.B 'S_Save as ...',$00
	DC.L $23E
	DC.W $2C
	DC.B 'Where is your old ClassAction program file?',$00
	DC.L $23F
	DC.W $12
	DC.B 'AppIcon left edge',$00
	DC.L $240
	DC.W $12
	DC.B 'AppIcon top edge',$00,$00
	DC.L $241
	DC.W $18
	DC.B 'Destination start path',$00,$00
	DC.L $242
	DC.W $E
	DC.B 'Public screen',$00
	DC.L $243
	DC.W $12
	DC.B 'Source start path',$00
	DC.L $244
	DC.W $E
	DC.B 'Show devices',$00,$00
	DC.L $245
	DC.W $E
	DC.B 'Delete icons',$00,$00
	DC.L $247
	DC.W $E
	DC.B 'Cached paths',$00,$00
	DC.L $248
	DC.W $E
	DC.B 'Path buttons',$00,$00
	DC.L $249
	DC.W $12
	DC.B 'Update on change',$00,$00
	DC.L $24A
	DC.W $8
	DC.B 'Refresh',$00
	DC.L $24B
	DC.W $C
	DC.B 'Lister font',$00
	DC.L $24C
	DC.W $A
	DC.B 'Menu font',$00
	DC.L $24D
	DC.W $C
	DC.B 'Background',$00,$00
	DC.L $24E
	DC.W $18
	DC.B 'Delete protected files',$00,$00
	DC.L $24F
	DC.W $A
	DC.B 'Path menu',$00
	DC.L $250
	DC.W $14
	DC.B 'Vertically arranged',$00
	DC.L $251
	DC.W $8
	DC.B 'H_Help',$00,$00
	DC.L $252
	DC.W $14
	DC.B 'Supported archives',$00,$00
	DC.L $253
	DC.W $10
	DC.B 'Open Images',$00,$00
	DC.L $257
	DC.W $6
	DC.B 'Async',$00
	DC.L $258
	DC.W $A
	DC.B 'Read dest',$00
	DC.L $25A
	DC.W $12
	DC.B 'Buffer size in KB',$00
	DC.L $25B
	DC.W $10
	DC.B 'Copy and delete',$00
	DC.L $25C
	DC.W $18
	DC.B 'Count files before copy',$00
	DC.L $25D
	DC.W $A
	DC.B 'Hide key',$00,$00
	DC.L $25E
	DC.W $C
	DC.B '?_Show help',$00
	DC.L $25F
	DC.W $A
	DC.B 'Popup key',$00
	DC.L $260
	DC.W $16
	DC.B 'Menu is pulldown menu',$00
	DC.L $261
	DC.W $24
	DC.B 'Replace older versions when copying',$00
	DC.L $262
	DC.W $1C
	DC.B 'Show version when replacing',$00
	DC.L $263
	DC.W $6
	DC.B 'Name',$00,$00
	DC.L $264
	DC.W $6
	DC.B 'Path',$00,$00
	DC.L $265
	DC.W $E
	DC.B 'List of Paths',$00
	DC.L $266
	DC.W $A
	DC.B 'Open with',$00
	DC.L $267
	DC.W $A
	DC.B 'Path list',$00
	DC.L $268
	DC.W $E
	DC.B 'Move path up',$00,$00
	DC.L $269
	DC.W $10
	DC.B 'Move path down',$00,$00
	DC.L $26A
	DC.W $A
	DC.B 'Add path',$00,$00
	DC.L $26B
	DC.W $C
	DC.B 'Remove path',$00
	DC.L $26C
	DC.W $18
	DC.B 'Please specify the path',$00
	DC.L $26D
	DC.W $26
	DC.B 'Please enter the title for the path:',$00,$00
	DC.L $26E
	DC.W $1A
	DC.B 'Path buttons transparent',$00,$00
	DC.L $26F
	DC.W $8
	DC.B 'Volume',$00,$00
	DC.L $270
	DC.W $1E
	DC.B 'This class cannot be deleted.',$00
	DC.L $271
	DC.W $16
	DC.B 'Image for this class',$00,$00
	DC.L $272
	DC.W $6
	DC.B 'Image',$00
	DC.L $273
	DC.W $16
	DC.B 'Choose an image file',$00,$00
	DC.L $274
	DC.W $12
	DC.B 'Use class images',$00,$00
	DC.L $275
	DC.W $C
	DC.B 'Own screen',$00,$00
	DC.L $276
	DC.W $8
	DC.B 'Archive',$00
	DC.L $277
	DC.W $14
	DC.B 'Check only patterns',$00
	DC.L $27A
	DC.W $A
	DC.B 'Duplicate',$00
	DC.L $27B
	DC.W $6
	DC.B 'Paste',$00
	DC.L $27C
	DC.W $6
	DC.B 'Learn',$00
	DC.L $27D
	DC.W $8
	DC.B 'Import',$00,$00
	DC.L $27E
	DC.W $8
	DC.B 'Export',$00,$00
	DC.L $27F
	DC.W $6
	DC.B 'Copy',$00,$00
	DC.L $280
	DC.W $6
	DC.B 'Blue',$00,$00
	DC.L $281
	DC.W $C
	DC.B 'Date format',$00
	DC.L $282
	DC.W $E
	DC.B 'Export class',$00,$00
	DC.L $283
	DC.W $6
	DC.B 'Green',$00
	DC.L $284
	DC.W $E
	DC.B 'Import class',$00,$00
	DC.L $285
	DC.W $4
	DC.B 'Red',$00
	DC.L $286
	DC.W $C
	DC.B 'Use ExAll()',$00
	DC.L $287
	DC.W $14
	DC.B 'Reaction requesters',$00
	DC.L $288
	DC.W $10
	DC.B 'Work directory',$00,$00
	DC.L $289
	DC.W $8
	DC.B 'source',$00,$00
	DC.L $28A
	DC.W $C
	DC.B 'destination',$00
	DC.L $28B
	DC.W $C
	DC.B 'program dir',$00
	DC.L $28C
	DC.W $4
	DC.B 'CD',$00,$00
	DC.L $28D
	DC.W $10
	DC.B 'Confirm delete',$00,$00
	DC.L $28E
	DC.W $18
	DC.B 'Files per ExAll() call',$00,$00

	ENDC ; CATCOMP_BLOCK


;-----------------------------------------------------------------------------


   STRUCTURE LocaleInfo,0
	APTR li_LocaleBase
	APTR li_Catalog
   LABEL LocaleInfo_SIZEOF

	IFD CATCOMP_CODE

	XREF      _LVOGetCatalogStr
	XDEF      _GetString
	XDEF      GetString
GetString:
_GetString:
	lea       CatCompBlock(pc),a1
	bra.s     2$
1$: move.w  (a1)+,d1
	add.w     d1,a1
2$: cmp.l   (a1)+,d0
	bne.s     1$
	addq.l    #2,a1
	move.l    (a0)+,d1
	bne.s     3$
	move.l    a1,d0
	rts
3$: move.l  a6,-(sp)
	move.l    d1,a6
	move.l    (a0),a0
	jsr       _LVOGetCatalogStr(a6)
	move.l    (sp)+,a6
	rts
	END

	ENDC ; CATCOMP_CODE


;-----------------------------------------------------------------------------


	ENDC ; CLASSACTIONPREFSCD_I
