#!/usr/bin/env python3
"""
Build ClassActionPrefs_res_embed.c from Storm ReActor ClassActionPrefs_res.o
+ CatComp objects/ClassActionPrefsCD.o.

SAS/C slink Error 611 rejects the Storm object's odd-address RELOC32 sites.
"""
from __future__ import print_function

import struct
import sys
from pathlib import Path

HUNK_UNIT = 0x3E7
HUNK_NAME = 0x3E8
HUNK_CODE = 0x3E9
HUNK_DATA = 0x3EA
HUNK_BSS = 0x3EB
HUNK_RELOC32 = 0x3EC
HUNK_EXT = 0x3EF
HUNK_SYMBOL = 0x3F0
HUNK_DEBUG = 0x3F1
HUNK_END = 0x3F2

EXT_DEF = 1
EXT_ABS = 2
EXT_REF32 = 129


def read_u32(buf, off):
    return (buf[off] << 24) | (buf[off + 1] << 16) | (buf[off + 2] << 8) | buf[off + 3]


def write_u32(buf, off, val):
    val &= 0xFFFFFFFF
    buf[off] = (val >> 24) & 0xFF
    buf[off + 1] = (val >> 16) & 0xFF
    buf[off + 2] = (val >> 8) & 0xFF
    buf[off + 3] = val & 0xFF


def parse_object(path):
    data = path.read_bytes()
    i = 0
    payload = None
    relocs = []
    defs = {}
    abs_defs = {}
    refs = []

    while i + 4 <= len(data):
        hunk = struct.unpack(">I", data[i : i + 4])[0]
        i += 4
        if hunk in (HUNK_UNIT, HUNK_NAME):
            n = struct.unpack(">I", data[i : i + 4])[0]
            i += 4 + n * 4
        elif hunk in (HUNK_CODE, HUNK_DATA):
            n = struct.unpack(">I", data[i : i + 4])[0]
            i += 4
            payload = bytearray(data[i : i + n * 4])
            i += n * 4
        elif hunk == HUNK_BSS:
            i += 4
        elif hunk == HUNK_RELOC32:
            while True:
                cnt = struct.unpack(">I", data[i : i + 4])[0]
                i += 4
                if cnt == 0:
                    break
                i += 4  # hunk number
                for _ in range(cnt):
                    relocs.append(struct.unpack(">I", data[i : i + 4])[0])
                    i += 4
        elif hunk in (HUNK_EXT, HUNK_SYMBOL):
            while True:
                typelen = struct.unpack(">I", data[i : i + 4])[0]
                i += 4
                if typelen == 0:
                    break
                typ = (typelen >> 24) & 0xFF
                nlongs = typelen & 0xFFFFFF
                name = data[i : i + nlongs * 4].split(b"\0")[0].decode("ascii")
                i += nlongs * 4
                if typ in (EXT_DEF, EXT_ABS, 3):
                    val = struct.unpack(">I", data[i : i + 4])[0]
                    i += 4
                    if typ == EXT_ABS:
                        abs_defs[name] = val
                    else:
                        defs[name] = val
                elif typ == EXT_REF32:
                    cnt = struct.unpack(">I", data[i : i + 4])[0]
                    i += 4
                    for _ in range(cnt):
                        refs.append((name, struct.unpack(">I", data[i : i + 4])[0]))
                        i += 4
                elif typ in (130,):
                    i += 4
                elif typ in (131, 132, 133, 134, 135):
                    cnt = struct.unpack(">I", data[i : i + 4])[0]
                    i += 4 + 4 * cnt
                else:
                    raise SystemExit("%s: unsupported EXT type %d for %r" % (path, typ, name))
        elif hunk == HUNK_DEBUG:
            n = struct.unpack(">I", data[i : i + 4])[0]
            i += 4 + n * 4
        elif hunk == HUNK_END:
            break
        else:
            raise SystemExit("%s: unknown hunk 0x%X at %d" % (path, hunk, i - 4))

    if payload is None:
        raise SystemExit("%s: no code/data hunk" % path)
    return {
        "payload": payload,
        "relocs": relocs,
        "defs": defs,
        "abs_defs": abs_defs,
        "refs": refs,
    }


def emit_c(out_path, blob, fixups, rct_off):
    lines = []
    lines.append("/* Generated by embed_rct_res.py - do not edit. */")
    lines.append("/* Storm ReActor RCT + CatComp strings with runtime reloc fixup")
    lines.append(" * (SAS/C slink rejects odd-address RELOC32 in ClassAction_res.o). */")
    lines.append("#include <exec/types.h>")
    lines.append("")
    lines.append("#define CA_RCT_HUNK_SIZE %dL" % len(blob))
    lines.append("#define CA_RCT_RESOURCE_OFF %dL" % rct_off)
    lines.append("#define CA_RCT_FIXUP_COUNT %dL" % len(fixups))
    lines.append("")
    lines.append("__far unsigned char ca_rct_hunk[CA_RCT_HUNK_SIZE] = {")
    row = []
    for idx, b in enumerate(blob):
        row.append("%d" % b)
        if len(row) == 16:
            lines.append(",".join(row) + ",")
            row = []
    if row:
        lines.append(",".join(row))
    lines.append("};")
    lines.append("")
    lines.append("static const ULONG ca_rct_fixups[CA_RCT_FIXUP_COUNT] = {")
    row = []
    for idx, off in enumerate(fixups):
        row.append("%luUL" % off)
        if len(row) == 8:
            lines.append(",".join(row) + ",")
            row = []
    if row:
        lines.append(",".join(row))
    lines.append("};")
    lines.append("")
    lines.append("__far char *RCTResource;")
    lines.append("")
    lines.append("void CA_FixupRCTResource(void)")
    lines.append("{")
    lines.append("\tULONG base;")
    lines.append("\tULONG i;")
    lines.append("\tULONG off;")
    lines.append("\tULONG val;")
    lines.append("\tUBYTE *p;")
    lines.append("\tstatic int done;")
    lines.append("")
    lines.append("\tif( done ) return;")
    lines.append("\tdone = 1;")
    lines.append("")
    lines.append("\tbase = (ULONG)ca_rct_hunk;")
    lines.append("\tRCTResource = (char *)ca_rct_hunk + CA_RCT_RESOURCE_OFF;")
    lines.append("")
    lines.append("\tfor( i = 0; i < CA_RCT_FIXUP_COUNT; i++ )")
    lines.append("\t{")
    lines.append("\t\toff = ca_rct_fixups[i];")
    lines.append("\t\tp = ca_rct_hunk + off;")
    lines.append("\t\tval = ((ULONG)p[0] << 24) | ((ULONG)p[1] << 16) |")
    lines.append("\t\t      ((ULONG)p[2] << 8) | (ULONG)p[3];")
    lines.append("\t\tval += base;")
    lines.append("\t\tp[0] = (UBYTE)(val >> 24);")
    lines.append("\t\tp[1] = (UBYTE)(val >> 16);")
    lines.append("\t\tp[2] = (UBYTE)(val >> 8);")
    lines.append("\t\tp[3] = (UBYTE)val;")
    lines.append("\t}")
    lines.append("}")
    lines.append("")
    out_path.write_text("\n".join(lines) + "\n", encoding="ascii")


def main():
    root = Path(__file__).resolve().parent
    rct_path = root / "ClassActionPrefs_res.o"
    cd_path = root / "objects" / "ClassActionPrefsCD.o"
    out_path = root / "ClassActionPrefs_res_embed.c"

    if len(sys.argv) > 1:
        out_path = Path(sys.argv[1])

    rct = parse_object(rct_path)
    cd = parse_object(cd_path)

    if "_RCTResource" not in rct["defs"]:
        raise SystemExit("ClassActionPrefs_res.o missing _RCTResource")

    rct_len = len(rct["payload"])
    cd_off = (rct_len + 3) & ~3
    blob = bytearray(cd_off + len(cd["payload"]))
    blob[0:rct_len] = rct["payload"]
    blob[cd_off : cd_off + len(cd["payload"])] = cd["payload"]

    fixups = []

    for off in rct["relocs"]:
        fixups.append(off)

    for off in cd["relocs"]:
        site = cd_off + off
        addend = read_u32(blob, site)
        write_u32(blob, site, addend + cd_off)
        fixups.append(site)

    for name, off in rct["refs"]:
        if name in rct["abs_defs"] or name in cd["abs_defs"]:
            abs_map = rct["abs_defs"] if name in rct["abs_defs"] else cd["abs_defs"]
            write_u32(blob, off, abs_map[name])
            continue
        if name in rct["defs"]:
            write_u32(blob, off, rct["defs"][name])
            fixups.append(off)
            continue
        key = name
        if key not in cd["defs"] and key.startswith("_") and key[1:] in cd["defs"]:
            key = key[1:]
        if key not in cd["defs"] and ("_" + key) in cd["defs"]:
            key = "_" + key
        if key not in cd["defs"]:
            raise SystemExit("unresolved RCT ref %r at %d" % (name, off))
        write_u32(blob, off, cd_off + cd["defs"][key])
        fixups.append(off)

    seen = set()
    uniq = []
    for off in fixups:
        if off in seen:
            continue
        seen.add(off)
        uniq.append(off)
    uniq.sort()

    rct_off = rct["defs"]["_RCTResource"]
    emit_c(out_path, blob, uniq, rct_off)
    print(
        "Wrote %s (%d bytes hunk, %d fixups, RCTResource +%d)"
        % (out_path, len(blob), len(uniq), rct_off)
    )


if __name__ == "__main__":
    main()
